### ISSUE TITLE
Tail specific container logs

### ISSUE THREAD

**Issue by eLco** [k14s/kapp#103]
Hi,

this isn't much of the bug, but more like a feature.

In the case of multiple containers per pod, someone may want to tail logs of specific containers in pod.
This can be the case during deployment of application with an Istio sidecar container for example, where developer may only want to see his/her application container logs, not istio-proxy wall of logs.

This relates to both kapp logs command and to kapp deploy --logs flag.
For the kapp deploy command new annotation can be used to include container names -
"kapp.k14s.io/container-logs: "container-name1, container2-name,.." OR current annotation can be reused 'kapp.k14s.io/deploy-logs: ""' for all container logs and "kapp.k14s.io/deploy-logs: "container-name1, container2-name,.." for specific ones.

I'm happy to work on this feature.

**Comment by cppforlife** [comment]
> For the kapp deploy command new annotation can be used to include container names -
"kapp.k14s.io/container-logs: "container-name1, container2-name,.." OR current annotation can be reused 'kapp.k14s.io/deploy-logs: ""' for all container logs and "kapp.k14s.io/deploy-logs: "container-name1, container2-name,.." for specific ones.

let's add a new annotation `kapp.k14s.io/deploy-logs-container-names: "name1,name2..."`

**Comment by eLco** [comment]
Both parts of this feature were merged.

**Comment by cppforlife** [comment]
included in https://github.com/k14s/kapp/releases/tag/v0.25.0
