### ISSUE TITLE
Releasing resources

### ISSUE THREAD

**Issue by bryanl** [k14s/kapp#111]
Is there a way to "release" a resource from kapp? For example, if I use `kapp deploy -a my-app` that creates a service and a deployment, how can I ensure the service doesn't get destroyed when I run `kapp delete a my-app`?

**Comment by cppforlife** [comment]
`kapp.k14s.io/delete-strategy: orphan` (https://github.com/k14s/kapp/blob/develop/docs/apply.md#controlling-apply-via-resource-annotations) would do that. im curious what kind of cases you are thinking of?

**Comment by bryanl** [comment]
Thanks!
