### ISSUE TITLE
panic: Missing template version 

### ISSUE THREAD

**Issue by universam1** [k14s/kapp#114]
Kapp errors out with a very unspecific error message.

```
panic: Missing template version 
```
Really hard to debug since `kubectl apply` works fine.
At least this message should print the resource it  errors on.

Thanks

**Comment by cppforlife** [comment]
@universam1 improved unexpected error msg here: https://github.com/k14s/kapp/commit/a5d09876ea628695323920e7a86bddab9a7fb912. can you include which kapp version you are using?

im guessing some resource is being picked up and being considered to be a templated resource. would you be able to build from develop (`./hack/build.sh && ./kapp version`) and share improved error output?

**Comment by universam1** [comment]
@cppforlife Thank you for that patch - This helped actually, I could get it resolved!

Compiled from develop it outputted:
```
╰─➤ ./kapp --version                                                                                                                                            
kapp version 0.28.0

Succeeded
```
Could this be released soon?

**Comment by cppforlife** [comment]
> I could get it resolved!

would you mind sharing what was the problem?

> Could this be released soon?

ill try to cut a release today.

**Comment by universam1** [comment]
> would you mind sharing what was the problem?

Sure, it will be off topic though. The problem was that helm templating using dashes `{{ ... -}}` was swallowing line breaks, wrapping two lines together, making the yaml definition partially broken. Interestingly that did not error out using `kubectl` but it did using `kapp`. Now this might be a very corner case but it shows how hard it is to track back without any context.

Thanks!

**Comment by cppforlife** [comment]
err msg improvement included in https://github.com/k14s/kapp/releases/tag/v0.29.0
