### ISSUE TITLE
Kapp should be able to deploy not only Yaml file, but also JSON array

### ISSUE THREAD

**Issue by yuezhizizhang** [k14s/kapp#118]
In HTTP request body, we usually send JSON data. To pass YAML files string in the JSON data, we will serialize it to an JSON array, like below:

`{
		"manifest": 
      "[{apiVersion: v1, kind: Service, metadata: {labels: {app: antrea}, name: antrea-octant, namespace: kube-system}, spec: {ports: [{port: 80, targetPort: 80}], selector: {app: antrea, component: antrea-octant}, type: NodePort}}, {apiVersion: apps/v1, kind: Deployment, metadata: {labels: {app: antrea, component: antrea-octant}, name: antrea-octant, namespace: kube-system}, spec: {replicas: 1, selector: {matchLabels: {app: antrea, component: antrea-octant}}, strategy: {type: Recreate}, template: {metadata: {labels: {app: antrea, component: antrea-octant}}, spec: {containers: [{args: ['-v'], command: [octant], env: [{name: OCTANT_ACCEPTED_HOSTS, value: 0.0.0.0}, {name: OCTANT_LISTENER_ADDR, value: '0.0.0.0:80'}, {name: OCTANT_DISABLE_OPEN_BROWSER, value: 'true'}, {name: KUBECONFIG, value: /kube/admin.conf}], image: 'antrea/octant-antrea-ubuntu:latest', imagePullPolicy: IfNotPresent, name: antrea-octant, ports: [{containerPort: 80}], volumeMounts: [{mountPath: /kube/, name: kubeconfig}]}], priorityClassName: system-cluster-critical, tolerations: [{key: CriticalAddonsOnly, operator: Exists}, {effect: NoSchedule, key: node-role.kubernetes.io/master}], volumes: [{name: kubeconfig, secret: {defaultMode: 256, secretName: octant-kubeconfig}}]}}}}]"
}`

When we call kapp to deploy this JSON array, kapp returns with an error:

    "message": "cannot create octant app: kapp: Error: error unmarshaling JSON: json: cannot unmarshal array into Go value of type map[string]interface {}\n: Deploying: exit status 1"

It's because kapp could only accept YAML file, and when it receives an YAML file, it split it with:

`const yamlSeparator = "\n---"`

For each split YAML file, it call YAMLToJSON to convert it to decode it. But it's not able to convert an JSON array to an interface{} struct. 

As we know, in Kubernetes, a JSON array or a multiple YAML file are equal. Hence, kapp should be more flexible with the input.

**Comment by cppforlife** [comment]
> As we know, in Kubernetes, a JSON array or a multiple YAML file are equal. Hence, kapp should be more flexible with the input.

i dont think i've seen kubernetes use JSON array of resources as an alternative to YAML stream with multiple YAML documents. unless its explicitly called out somewhere in k8s docs/api definitions/kubectl usage, i dont think it would makes sense for kapp to support it.

**Comment by yuezhizizhang** [comment]
client-go doesn't bias JSON from YAML. One of an important interfaces of Kubernetes, which is decoding the []byte into Kubernetes objects, accepts both JSON or YAML data:

`func Decode(data []byte) (runtime.Object, error) {
    decode := scheme.Codecs.UniversalDeserializer().Decode
    obj, _, err := decode(data, nil, nil)
    return obj, err
}`

So the question becomes how to split YAML or JSON array. For YAML, we split multiple files by separator "\n---\n", for JSON array, we loop through the array.

As I mentioned earlier, YAML and JSON are somewhat equivalent. When you serialize a YAML, it becomes JSON.

**Comment by cppforlife** [comment]
a lot of places that accept YAML happen to work for JSON because JSON is valid YAML subset. this even works for something like this:

```yaml
{"foo": 123}
---
{"bar": 123}
```

> So the question becomes how to split YAML or JSON array. For YAML, we split multiple files by separator "\n---\n", for JSON array, we loop through the array.

it's not correct to assume that JSON array is an array of several k8s resources. what if it's just trying to represent one thing that happens to be an array?

i did check on kubectl apply -f- and it seems to accept a stream of well-formed JSON objects (ie `{...}{...}`) (there is also jsonl format that separates JSON objects by newline to enable streaming use cases), but that's not in the array format (it throws an error if its wrapped as an array).

> When you serialize a YAML, it becomes JSON.

that's not correct. JSON is valid YAML, but YAML is not valid JSON.

to address your initial question:

> To pass YAML files string in the JSON data, we will serialize it to an JSON array, like below:

instead of doing that lots of UIs keep envelope in JSON format; however, contents of individual keys are YAML strings. eg

```json
{ "manifest": "apiVersion: v1\nkind: ConfigMap\n..." }
```

**Comment by yuezhizizhang** [comment]
> { "manifest": "apiVersion: v1\nkind: ConfigMap\n..." }

This is only a single Object, but when we deploy an app, there is more than one object we have to deploy, for instance, a simplest one would require a service and deployment. In this case, how should we do? If we call Kapp deploy multiple times, by default, Kapp will do a diff and delete the previous deployed resources for the same app. So the only way we should do is combine them to a single string and pass it to Kapp deploy. So the key here is how to represent a combined YAML file is JSON. That is, a JSON array.

**Comment by cppforlife** [comment]
> This is only a single Object

i should have been more explicit here. this approach isnt for a single k8s resource. its for the entier YAML stream serialized. that's why it's YAML docs are separated by `---`. eg.

```yaml
{ "manifest": "apiVersion: v1\nkind: ConfigMap\n...\n---\napiVersion: v1\nkind: Secret\n..." }
```

**Comment by cppforlife** [comment]
closing this issue. ^ answered in the above comment. feel free to reopen if it's not working out for some reason.
