### ISSUE TITLE
Deploy fails due to `PodDisruptionBudget` change

### ISSUE THREAD

**Issue by elsbrock** [k14s/kapp#126]
I am trying to deploy an application that uses a `PodDisruptionBudget`. I have previously deployed the application using `helm` and would now like to give `kapp` a try (using v0.31.0) . `kapp` updates all resources because it applies its labels.

In the `helm` Chart I have

```
helm.sh/hook: post-upgrade,post-install
helm.sh/hook-delete-policy: before-hook-creation
```

set on the PDB, which would instruct helm to recreate the resource upon upgrades. It looks like with `kapp` I am out of luck and need to delete it manually. Is that an oversight or intended? I am not saying that `kapp` should understand `helm` annotations, but should it treat PodDisruptionBudgets in a special way?

```
10:07:51PM: ---- applying 17 changes [0/42 done] ----
10:07:51PM: update poddisruptionbudget/example-backend (policy/v1beta1) namespace: default

kapp: Error: Applying update poddisruptionbudget/example-backend (policy/v1beta1) namespace: default:
  Updating resource poddisruptionbudget/example-backend (policy/v1beta1) namespace: default:
    PodDisruptionBudget.policy "example-backend" is invalid: spec:
      Forbidden: updates to poddisruptionbudget spec are forbidden. (reason: Invalid)
```

I am running k8s v1.14; as far as I know PDB recreation should be done automatically from v1.15 on.

**Comment by cppforlife** [comment]
kapp has a rich support for resource lifecycle given various nuances resources may have. check out update strategy for your use case: https://github.com/k14s/kapp/blob/develop/docs/apply.md#kappk14sioupdate-strategy. you can use fallback-on-replace or always-replace.

**Comment by elsbrock** [comment]
Thank you!
