### ISSUE TITLE
Allow user to opt-out of specific ownershipLabelRules

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/kapp#130]
For example, allow kapp to adopt a StatefulSet without needing to recreate volume claims by being able to disable: 

https://github.com/k14s/kapp/blob/be68a32cd96e6f84c8f4ce7f75c982164ed2fd69/pkg/kapp/config/default.go#L164-L171

src: https://kubernetes.slack.com/archives/CH8KCCKA5/p1596493417409400

**Comment by cppforlife** [comment]
Added `kapp.k14s.io/disable-default-ownership-label-rules` annotation in https://github.com/k14s/kapp/releases/tag/v0.33.0.

For statefulset use case above, dont forget to _also_ add `kapp.k14s.io/disable-label-scoping` annotation (or newly named `kapp.k14s.io/disable-default-label-scoping-rules`).
