### ISSUE TITLE
Allow kapp Config to be defined by vanilla k8s resources

### ISSUE THREAD

**Issue by scothis** [k14s/kapp#131]
The `kapp.k14s.io` `Config` "resource" is a handy way to provide hints to kapp to make managing a deployment even better. However, its presence limits compatibility with other tools, like kubectl. I'd like to be able to define a single release distribution that can be installed with either kapp or kubectl depending on the user's desire.

If I could define the content of the Config resource is a vanilla k8s resource like a ConfigMap, then kubectl would be able to apply the release without choking on an unknown resource.

An alternate solution would be to define the Config's concepts as annotations on the targeted resource. This could be done for `rebaseRules` by dropping the matcher, but may not translate well for all config concepts.

**Comment by gcheadle-vmware** [comment]
Hi @scothis, 

Interesting suggestion, thank you for pointing this out! It's important to us that our tools play nicely with other tools.

A ConfigMap seems like a sensible approach, we could devise an annotation (i.e. kapp.k14s.kapp.io/config) to distinguish a kapp Config from a ConfigMap. 

Are there specifics about this circumstance that makes separating your kapp-specfic config files into a different directory difficult? If that were possible, then the instructions for using kapp could be just adding an optional second -f.

**Comment by scothis** [comment]
> Are there specifics about this circumstance that makes separating your kapp-specfic config files into a different directory difficult? If that were possible, then the instructions for using kapp could be just adding an optional second -f.

That's how I have the source setup. But for releases I need both a kapp and non-kapp distribution.

**Comment by cppforlife** [comment]
implemented in https://github.com/k14s/kapp/commit/e62d79a86d884c40cb1ed49235bda7e116234834. will be available in next release.

**Comment by cppforlife** [comment]
included in https://github.com/k14s/kapp/releases/tag/v0.34.0
