### ISSUE TITLE
multi-namespace rbac listing of resources

### ISSUE THREAD

**Issue by erSitzt** [k14s/kapp#132]
Hi,

i have users with permissions only on specific namespaces who dont get any resources listed when using kapp inspect

```
❯ kapp list -n kapp-apps
Target cluster 'https://rancher.mydomain.com/k8s/clusters/c-p5rfh' (nodes: k8s-zentrale-qa-worker3, 9+)

Apps in namespace 'kapp-apps'

Name                                Namespaces  Lcs   Lca
...more services...
jwtauth-vslive                      neo         true  7d
...more services...

Lcs: Last Change Successful
Lca: Last Change Age

40 apps

Succeeded
```

But when i do a `kapp inspect` i get this
```
❯ kapp inspect -n kapp-apps -a jwtauth-vslive
Target cluster 'https://rancher.mydomain.com/k8s/clusters/c-p5rfh' (nodes: k8s-zentrale-qa-worker3, 9+)

Resources in app 'jwtauth-vslive'

Namespace  Name  Kind  Owner  Conds.  Rs  Ri  Age

Rs: Reconcile state
Ri: Reconcile information

0 resources

Succeeded
```

If i use `kubectl`with the kapp label and using the same kubeconfig i get this

```
❯ kubectl get all,destinationrule,virtualservice -n neo -l kapp.k14s.io/app=1596124003941685384
NAME                                  READY   STATUS    RESTARTS   AGE
pod/jwtauth-vslive-5457594d5f-hvqhm   2/2     Running   0          7d17h

NAME                     TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/jwtauth-vslive   ClusterIP   10.43.163.45   <none>        8888/TCP   7d17h

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/jwtauth-vslive   1/1     1            1           7d17h

NAME                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/jwtauth-vslive-5457594d5f   1         1         1       7d17h

NAME                                                 HOST                                   AGE
destinationrule.networking.istio.io/jwtauth-vslive   jwtauth-vslive.neo.svc.cluster.local   7d17h

NAME                                                GATEWAYS                                 HOSTS                                                                                            AGE
virtualservice.networking.istio.io/jwtauth-vslive   [istio-gateways/standard-gateway mesh]   [jwtauth-neo.mydomain.com jwtauth-vslive.neo.svc.cluster.local jwtauth-neo.myotherdomain.com]   7d17h
```

kapp is not throwing any error as far as i can see. 
any idea what is happening ? 
the user has permissions on both namespaces in this example (neo and kapp-apps)

regards 
Dennis

**Comment by erSitzt** [comment]
I guess kapp is querying resources for all namespaces and filtering based on labels afterwards ?

this is what happens with the same user when using `--all-namespaces` with `kubectl`

```
❯ kubectl get pods --all-namespaces
Error from server (Forbidden): pods is forbidden: User "u-mvvzrgo5mc" cannot list resource "pods" in API group "" at the cluster scope
❯ kubectl get pods -n neo
NAME                                       READY   STATUS    RESTARTS   AGE
...
jwtauth-vslive-5457594d5f-hvqhm            2/2     Running   0          7d17h
...
```

**Comment by erSitzt** [comment]
If it helps i can list the `ClusterRoles` for that user.

He has
`admin` ( and `project-owner` which comes from rancher i guess) on namespace `neo`
`edit `( and `project-member` ) on namespace `kapp-apps`

 `admin` and `edit `are kubernetes defaults i guess ?

**Comment by cppforlife** [comment]
check this doc page out: https://github.com/k14s/kapp/blob/develop/docs/rbac.md#running-kapp-under-restricted-permissions. im guessing second bullet is probably what you are missing. kapp does not know which namespaces it needs to query so it falls back to only using kapp-apps namespace.

one improvement i can see to be made to kapp is for kapp to fall back to set of namespaces it initially observed when deploying.

**Comment by erSitzt** [comment]
oh.. my bad, i was looking through the issues but not the docs :(

I will check with adjusted permissions to list namespaces

thanks !

**Comment by erSitzt** [comment]
Ok, so using Ranchers Permissions-Model you need "View All Projects" on the cluster in questions, this includes listing all namespaces in the cluster.

It`s working now

**Comment by erSitzt** [comment]
@cppforlife thanks again for your help !
