### ISSUE TITLE
Secret contents stored in plain-text in `kapp.k14s.io/original` annotation

### ISSUE THREAD

**Issue by davewalter** [k14s/kapp#137]
@angelachin and I noticed that kapp-deployed secrets include the contents of the secret in plain-text in the `kapp.k14s.io/original` annotation. While we know that Secrets aren't particularly secure, since the data is simply base64 encoded, it still feels insecure to include the data unencoded.

**Comment by cppforlife** [comment]
@davewalter answered here: https://github.com/k14s/kapp/issues/90#issuecomment-602074356
