### ISSUE TITLE
kapp delete --wait flag

### ISSUE THREAD

**Issue by ntalekt** [k14s/kapp#143]
**Feature request**: `kapp delete --wait` flags.

Currently `kapp deploy` has several wait flags such as:

```
--wait
--wait-check-internal duration
--wait-concurrency int
--wait-ignored
--wait-timeout duration
```

Possible to get the same functionality on the `kapp delete` app command?

**Comment by cppforlife** [comment]
@ntalekt delete has the exactly same flags already (check out kapp delete -h; flags are not grouped though like in deploy).

**Comment by ntalekt** [comment]
@cppforlife and thank you for pointing out that I obviously can't read what's right in front of my face.
