### ISSUE TITLE
Add Shell Autocompletion 

### ISSUE THREAD

**Issue by danielhelfand** [k14s/kapp#155]
When working with `kapp` outside of CI (e.g., working locally to develop a process that can be used in CI), it would be nice to have shell autocompletion to allow for a user to tab to autocomplete commands. This would be similar to what is outlined for [`kubectl`](https://kubernetes.io/docs/tasks/tools/install-kubectl/#enabling-shell-autocompletion). 

When a user tabs after having `kapp`, all possible commands should be displayed:

```
kapp \t

delete deploy inspect ...
```

When typing a command that has been started, autocomplete should complete the command:

```
kapp dep \t -> kapp deploy
```

**Describe alternatives you've considered**

I could generate the autocompletion scripts myself and maintain outside the project, but I feel like it's a pretty common use case that should be simple to support.

**Additional context**
[Cobra docs](https://github.com/spf13/cobra/blob/142dfb15a8b9122dd6543adc769cbf59b976d793/shell_completions.md)

**Comment by cppforlife** [comment]
added https://github.com/k14s/kapp/commit/09e930d0a7267398435772533a08e7bd31d7df9b and https://github.com/k14s/kapp/commit/c4fb76958fc73e6709a8952aa1c9822fef88e9e7

**Comment by danielhelfand** [comment]
Works great. Thank you!
