### ISSUE TITLE
kapp should double check that k8s api returns labeled resources

### ISSUE THREAD

**Issue by cppforlife** [k14s/kapp#160]
currently kapp trusts that k8s api returns resources based on the label query specified. it appears that if aggregated api impl come into play there is no guarantee that they return resources filted by label as requested (antrea for example did not implement label selector).

**Comment by danielhelfand** [comment]
As a question on this, would the result of this labeled resource check result in an error message to the user? Or is there some other plan for the recovery in this scenario?

**Comment by cppforlife** [comment]
> would the result of this labeled resource check result in an error message to the user

if resource is not appropriately labeled, then it would "eliminate" resource from further processing like diffing (== consider that resource as not being there). this would allow kapp to work with aggregated apis that do not behave up to spec.

**Comment by cari-lynn** [comment]
This is available in release [v0.36.0](https://github.com/vmware-tanzu/carvel-kapp/releases/tag/v0.36.0)
