### ISSUE TITLE
Deps are out of date

### ISSUE THREAD

**Issue by benmoss** [k14s/kapp#163]
- This project is on a [version of k8s from 2018](https://github.com/kubernetes/client-go/releases/tag/v8.0.0) 😱 .
- Go is still on 1.13
- Cobra has a new release that includes support for `context.Context` that might help with client-go's new use of contexts as well

I encountered this problem when trying to use a go.mod file to put a dependency on kapp and had it collide with other client-go dependent libraries

**Comment by joaopapereira** [comment]
Thanks for pointing it out. We are aware of this and we will try to get some of the dependencies up to date as soon as we can.
In the meanwhile, if anyone wants to try to solve one or all the dependencies we are open to reviewing PRs.

**Comment by danielhelfand** [comment]
Just wanted to reference the pull request (#162) that @benmoss had begun to open for this to get some idea around potential issues with updating.

**Comment by cppforlife** [comment]
> This project is on a version of k8s from 2018 😱 .

there wasnt any need to update k8s client-go since k8s api remained stable and we wanted to play nice with older clusters (that assumes that client-go might start using k8s apis that would havent been supported by older clusters).

> Go is still on 1.13

that we need to bump to go1.14

> Cobra has a new release that includes support for context.Context that might help with client-go's new use of contexts as well

wasnt any need so far for a bump, feature-wise.

**Comment by benmoss** [comment]
Yep, this isn't as important as I first thought, I misunderstood how client-go version skew works.
