### ISSUE TITLE
kapp rename should support optional --new-namespace

### ISSUE THREAD

**Issue by cppforlife** [k14s/kapp#165]
this would help scenarios where state configmap was dropped into a wrong namespace.

**Comment by iamhsk** [comment]
@cppforlife Is the intent behind this issue to move both the renamed app and the configmap to a different namespace? Or just the configmap? And in what situation a configmap would be dropped into a wrong namespace?

**Comment by renuy** [comment]
Only, the state configmap should be renamed. Label stays the same. Everything inside the configMap should remain the same.

**Comment by renuy** [comment]
@cppforlife , how should the behaviour be for following commands
1. kapp rename -a app --new-name
--is this a valid case? currently we do not validate presence of name parameter, but error out anyways later on.  should we mandate the presence of new-name?
2. kapp rename -a app --new-name app1
--this is normal use case. no issues here. 
3. kapp rename -a app --new-name app1 --new-namespace newNS
--change the name as well as namespace. again this is the new normal use case.
4. kapp rename -a app --new-namespace newNS
-- how should this be treated? Is this valid use case? This will not change the name, only create it in the new namespace
5. Does namespace change also apply to labeled apps? or only recorded apps
6. if the new-namespace does not exist, should it be created? or error out?

my views:
- if new-name and new-namespace, both are not provided then error out.
- if new-namespace does not exist, then error out. (do not create it) (are we in the business of creating namespace?)
- if new-name is not provided and only new-namespace is provided, then this is request to update the namespace. so go ahead and do it.

**Comment by renuy** [comment]
few more things, 
1. How should the history be treated for renaming?
2. should the history be also moved across namespace, if namespace is changed?

**Comment by renuy** [comment]
available in release v0.40.0
