### ISSUE TITLE
Unexpected result of diff-exit-status for app group deploy

### ISSUE THREAD

**Issue by twiechert** [k14s/kapp#166]
When passing the `diff-exit-status` flag to an app group deployment, kapp exits after checking the first app inside the app group.

When applied to app groups, I would expect kapp to exit after checking all apps inside the group and returning the exit status for the complete group (unchanged, any resource has changed etc.).

**Comment by danielhelfand** [comment]
Thanks for reporting this @twiechert. Would you mind sharing an example of how to reproduce this issue along with the associated usage of `kapp`? What version of `kapp` you are using will also help as well.
