### ISSUE TITLE
kapp is not working on WSL2/docker

### ISSUE THREAD

**Issue by lukasmrtvy** [k14s/kapp#179]
**What steps did you take:**
```
FROM ubuntu:latest

ENV KAPP_VERISON 0.35.0

RUN \
  apt update && apt install -y curl && \
  curl -sSL "https://github.com/vmware-tanzu/carvel-kapp/releases/download/v${KAPP_VERSION}/kapp-linux-amd64" -o /usr/local/bin/kapp && chmod +x /usr/local/bin/kapp 

RUN kapp
```

**What happened:**
```
kapp
/usr/local/bin/kapp: line 1: Not: command not found
```
**What did you expect:**
kapp should run on WSL2/docker

**Anything else you would like to add:**
no

**Environment:**

- kapp version (use `kapp --version`): 0.35.0
- OS (e.g. from `/etc/os-release`): WSL2
- Kubernetes version (use `kubectl version`)

**Comment by danielhelfand** [comment]
Hey @lukasmrtvy,

We were able to reproduce this and actually had trouble with figuring it out too, but it looks like there is a typo in the Dockerfile above.

`ENV KAPP_VERISON 0.35.0` should be `ENV KAPP_VERSION 0.35.0` 

VERSION has the typo.

//cc @gcheadle-vmware @pivotal-dean

**Comment by lukasmrtvy** [comment]
oh, stupid me, sorry guys for bothering..
