### ISSUE TITLE
Add filtering by label

### ISSUE THREAD

**Issue by cameronbraid** [k14s/kapp#182]
I would like the ability to filter `kapp deploy` using label selectors

jenkins-x 3 will be switching to use kapp to apply resources to a cluster and as a jenkins-x 3 user I would like to use this in conjunction with okteto.

Okteto replaces deploymens with a developer containers to let you code on your app inside kubernetes.  It does this by rewriting the deployment resource.  It also adds a label to indicate that the deployment has been modified by okteto.

I wish to prevent kapp from overriding the okteto managed deployments which would be much easier to do by specifying a 'not' filter using a label selector.  

A possible workaround is to use kubectl to find all resources with the labels, and convert them into a resource filter using kinds and names.

**Comment by danielhelfand** [comment]
@cameronbraid Thanks for opening this. A couple questions:

1. Can you describe your workflow with okteto/kapp (i.e. what commands are you running with each/the manifests you are working with)? 

2. Are you running kapp locally or from within the okteto development container?

**Comment by cameronbraid** [comment]
My git-to-kubernetes process is as follows

1) I run kustomize to template my resources (with differing overlays for the dev/staging/live environment) into a stream
2) I pipe this stream into `kapp deploy` to install them in the cluster

When I am developing a new feature in ProjectA :

* I deploy the same resources into my development cluster as I have in my live cluster (steps 1 and 2 above)
* I run `okteto up` against my development cluster to replace the deployment of ProjectA with the okteto modified deployment
* I make the changes in cluster using vscode remote connection to the ProjectA development pod

Now say I also need to develop a new feature in ProjectB, so I perform the same steps as above but this time when I run `kapp deploy` I use the following filter `--filter '{"not":{"resource":{"kinds":["Deployment"], "names":["ProjectA"]}}}` to prevent kapp from overriding the ProjectA okteto  deployment 

This works at the moment because
* I know which projects I am working on
* I manually trigger the `kapp deploy` commands at the appropriate times

The 'filter by label selector' enhancement would allow me to write the above filter as : 

`--filter '{"not":{"resource":{"kinds":["Deployment"], "labels":["dev.okteto.com=true"]}}}`

This would then cause `kapp deploy` to leave **any** okteto enabled deployments as they are.

Once I have finished the new feature on ProjectB I do the following

* run okteto down which restores the deployment to how it was before
* perform a build and release of ProjectB
* update my resources in git to point to the new version pf ProjectB
* re-run `kustomize | kapp deploy --filter '{"not":{"resource":{"kinds":["Deployment"], "names":["ProjectA"]}}}` so the  latest version of ProjectB is applied to the cluster.  Note I must be sure to filter out any oktekto enabled deployments. 

What I want out of this feature is to be able to use the same filter expression each time I run kapp deploy - based on the label `dev.okteto.com=true`

**Comment by cameronbraid** [comment]
And for question 2) 
* I run this on my dev server outside the cluster
* with jenkins-x 3 I will be running kapp in the cluster in a jx-boot job
* I will never need to run kapp within the okteto development pod

**Comment by joaopapereira** [comment]
Because people would be more familiar with label selector in k8s maybe we can do our filtering based on [k8s labels selector](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/)

## Acceptance criteria
### Scenario 1
Install single application using `=` filter selector
**Given** I have the following gist https://gist.github.com/joaopapereira/1a127033d7d76693155a07d1c069f06f in the file system `app-deploy.yml`
**When** I run the command `kapp deploy -a simple-app -f app-deploy.yml --filter '{"and": {"resource": {"kinds": ["Deployment", "Service"], "labelSelector": "app=simple-app"}}'`
**Then** I should see
```
Changes

Namespace  Name        Kind        Conds.  Age  Op      Op st.  Wait to    Rs  Ri
default    simple-app  Deployment  -       -    create  -       reconcile  -   -
^          simple-app  Service     -       -    create  -       reconcile  -   -
```

### Scenario 2
Install single application using `!=` filter selector
**Given** I have the following gist https://gist.github.com/joaopapereira/1a127033d7d76693155a07d1c069f06f in the file system `app-deploy.yml`
**When** I run the command `kapp deploy -a simple-app -f app-deploy.yml --filter '{"and": {"resource": {"kinds": ["Deployment", "Service"], "labelSelector": "app!=other-app"}}'`
**Then** I should see
```
Changes

Namespace  Name        Kind        Conds.  Age  Op      Op st.  Wait to    Rs  Ri
default    simple-app  Deployment  -       -    create  -       reconcile  -   -
^          simple-app  Service     -       -    create  -       reconcile  -   -
```

### Scenario 3
Install single application using `in` filter selector
**Given** I have the following gist https://gist.github.com/joaopapereira/1a127033d7d76693155a07d1c069f06f in the file system `app-deploy.yml`
**When** I run the command `kapp deploy -a simple-app -f app-deploy.yml --filter '{"and": {"resource": {"kinds": ["Deployment", "Service"], "labelSelector": "app in (simple-app,other-app)"}}'`
**Then** I should see
```
Changes

Namespace  Name        Kind        Conds.  Age  Op      Op st.  Wait to    Rs  Ri
default    other-app   Deployment  -       -    create  -       reconcile  -   -
^          other-app   Service     -       -    create  -       reconcile  -   -
^          simple-app  Deployment  -       -    create  -       reconcile  -   -
^          simple-app  Service     -       -    create  -       reconcile  -   -
```
### Scenario 4
Install single application using `notin` filter selector
**Given** I have the following gist https://gist.github.com/joaopapereira/1a127033d7d76693155a07d1c069f06f in the file system `app-deploy.yml`
**When** I run the command `kapp deploy -a simple-app -f app-deploy.yml --filter '{"and": {"resource": {"kinds": ["Deployment", "Service"], "labelSelector": "app notin (simple-app,other-app)"}}'`
**Then** Nothing will be installed

---
@cameronbraid do you think these scenarios capture what you are looking for?

**Comment by cameronbraid** [comment]
My intent was for the label selectors to be based on k8s label selectors.

All of your scenarios seem to only consider what's in the filesystem, where as I need the label selector to be run against the resources in kubernetes.  Okteto only modifies the _in cluster resources_

**Comment by joaopapereira** [comment]
Ok, so I reworked a little bit of these scenarios to match the change and after some thinking a little bit more about these maybe `--filter` is not a good flag to use. At this point, the filter is used only for filtering based on the configuration that you provide `kapp`.
So to mitigate this our proposal is to create a new filtering system that would filter the differences between the cluster and local.

I reworked some of the above scenarios to match this new proposal. @cameronbraid does this match the scenario that you are looking for?

---

## Acceptance criteria

### Scenarios pre condition
Using gist https://gist.github.com/joaopapereira/1a127033d7d76693155a07d1c069f06f downloaded to your file system in `app-deploy.yml` file
We execute `kapp deploy -a my-app -f app-deploy.yml`

### Cluster resource label Scenarios
#### :books: Scenario 1
Does not update the `simple-app` when label selector uses `=` operation and cluster resource have the label

**Given** I add a label `change-me` with the value `no` to the Deployment with name `name: simple-app` directly in the cluster resource using `kubectl`
**When** I updated the `app-deploy.yml` to use the image `nginx` on the Deployment with name `name: simple-app`
**And** I run the command `kapp deploy -a my-app -f app-deploy.yml --diff-filter '{"not": {"clusterResource": {"labelSelector": "change-me=no"}}'`
**Then** Nothing will be updated

#### :books: Scenario 2
Does not update the `simple-app` when label selector uses `!=` operation and cluster resource have the label

**Given** I add a label `change-me` with the value `no` to the Deployment with name `name: simple-app` directly in the cluster resource using `kubectl`
**When** I updated the `app-deploy.yml` to use the image `nginx` on the Deployment with name `name: simple-app`
**And** I run the command `kapp deploy -a my-app -f app-deploy.yml --diff-filter '{"clusterResource": {"labelSelector": "change-me!=no"}'`
**Then** Nothing will be updated

#### :books: Scenario 3
Does not update the `simple-app` when label selector uses `in` operation and cluster resource have the label

**Given** I add a label `change-me` with the value `no` to the Deployment with name `name: simple-app` directly in the cluster resource using `kubectl`
**When** I updated the `app-deploy.yml` to use the image `nginx` on the Deployment with name `name: simple-app`
**And** I run the command `kapp deploy -a my-app -f app-deploy.yml --diff-filter '{"not": {"clusterResource": {"labelSelector": "change-me in (no)"}}'`
**Then** Nothing will be updated

#### :books: Scenario 4
Does not update the `simple-app` when label selector uses `notin` operation and cluster resource have the label

**Given** I add a label `change-me` with the value `no` to the Deployment with name `name: simple-app` directly in the cluster resource using `kubectl`
**When** I updated the `app-deploy.yml` to use the image `nginx` on the Deployment with name `name: simple-app`
**And** I run the command `kapp deploy -a my-app -f app-deploy.yml --diff-filter '{"clusterResource": {"labelSelector": "change-me notin (no)"}}'`
**Then** Nothing will be updated

### Local resource label Scenarios
#### :books: Scenario 5
Does not update the `simple-app` when label selector uses `=` operation and local resource have the label

**Given** I add a label `change-me` with the value `no` to the Deployment with name `name: simple-app` in the `app-deploy.yml` file
**When** I updated the `app-deploy.yml` to use the image `nginx` on the Deployment with name `name: simple-app`
**And** I run the command `kapp deploy -a my-app -f app-deploy.yml --diff-filter '{"not": {"localResource": {"labelSelector": "change-me=no"}}}'`
**Then** Nothing will be updated

#### :books: Scenario 6
Does not update the `simple-app` when label selector uses `!=` operation and local resource have the label

**Given** I add a label `change-me` with the value `no` to the Deployment with name `name: simple-app` in the `app-deploy.yml` file
**When** I updated the `app-deploy.yml` to use the image `nginx` on the Deployment with name `name: simple-app`
**And** I run the command `kapp deploy -a my-app -f app-deploy.yml --diff-filter '{"localResource": {"labelSelector": "change-me!=no"}'`
**Then** Nothing will be updated

#### :books: Scenario 7
Does not update the `simple-app` when label selector uses `in` operation and local resource have the label

**Given** I add a label `change-me` with the value `no` to the Deployment with name `name: simple-app` in the `app-deploy.yml` file
**When** I updated the `app-deploy.yml` to use the image `nginx` on the Deployment with name `name: simple-app`
**And** I run the command `kapp deploy -a my-app -f app-deploy.yml --diff-filter '{"not": {"localResource": {"labelSelector": "change-me in (no)"}}'`
**Then** Nothing will be updated

#### :books: Scenario 8
Does not update the `simple-app` when label selector uses `notin` operation and local resource have the label

**Given** I add a label `change-me` with the value `no` to the Deployment with name `name: simple-app` in the `app-deploy.yml` file
**When** I updated the `app-deploy.yml` to use the image `nginx` on the Deployment with name `name: simple-app`
**And** I run the command `kapp deploy -a my-app -f app-deploy.yml --diff-filter '{"localResource": {"labelSelector": "change-me notin (no)"}}'`
**Then** Nothing will be updated

### Local and Cluster resource label Scenarios
#### :books: Scenario 9
Does not update the `simple-app` when label selector uses `=` operation when local and cluster have the change-me label

**Given** I add a label `change-me` with the value `no` to the Deployment with name `name: simple-app` in the `app-deploy.yml` file
**And** I add a label `change-me` with the value `no` to the Deployment with name `name: simple-app` directly in the cluster resource using `kubectl`
**When** I updated the `app-deploy.yml` to use the image `nginx` on the Deployment with name `name: simple-app`
**And** I run the command `kapp deploy -a my-app -f app-deploy.yml --diff-filter '{"and": [{"localResource": {"labelSelector": "change-me!=no"}}, {"clusterResource": {"labelSelector": "change-me!=no"}}]}'`
**Then** Nothing will be updated

#### :books: Scenario 10
Does not update the `simple-app` when label selector uses `=` operation when local resource has the change-me label with an OR operation

**Given** I add a label `change-me` with the value `no` to the Deployment with name `name: simple-app` in the `app-deploy.yml` file
**When** I updated the `app-deploy.yml` to use the image `nginx` on the Deployment with name `name: simple-app`
**And** I run the command `kapp deploy -a my-app -f app-deploy.yml --diff-filter '{"or": [{"localResource": {"labelSelector": "change-me!=no"}}, {"clusterResource": {"labelSelector": "change-me!=no"}}]}'`
**Then** Nothing will be updated

#### :books: Scenario 11
Does not update the `simple-app` when label selector uses `=` operation when cluster resource has the change-me label with an OR operation

**Given** I add a label `change-me` with the value `no` to the Deployment with name `name: simple-app` directly in the cluster resource using `kubectl`
**When** I updated the `app-deploy.yml` to use the image `nginx` on the Deployment with name `name: simple-app`
**And** I run the command `kapp deploy -a my-app -f app-deploy.yml --diff-filter '{"or": [{"localResource": {"labelSelector": "change-me!=no"}}, {"clusterResource": {"labelSelector": "change-me!=no"}}]}'`
**Then** Nothing will be updated

**Comment by cameronbraid** [comment]
Yep, looks like all of those scenarios are just different ways of expressing `exclude resource with label change-me=no`

That looks great thanks.

**Comment by cameronbraid** [comment]
I would also assume that multiple labels can be used.  for example exclude all resources labelled change-me=no OR kapp-ignore=yes

**Comment by joaopapereira** [comment]
Going to do an extra update on the scenarios above. We discussed the possibility of allow the user to have a more specific way to differentiate between local and cluster resources. Instead of 
`kapp deploy -a my-app -f app-deploy.yml --diff-filter '{"resource": {"labelSelector": "change-me notin (no)"}}'`
We might have:
`kapp deploy -a my-app -f app-deploy.yml --diff-filter '{"localResource": {"labelSelector": "change-me notin (no)"}}'`
`kapp deploy -a my-app -f app-deploy.yml --diff-filter '{"clusterResource": {"labelSelector": "change-me notin (no)"}}'`

Also updating the criteria above to give more examples with OR and AND

**Comment by cameronbraid** [comment]
May I suggest that kapp also support the same feature using annotations.

**Comment by cameronbraid** [comment]
Since the proposal has been accepted, are you able to give an idea of the timeframe ?

**Comment by aaronshurley** [comment]
@cameronbraid it's in our Prioritized Backlog but it's a bit of a way down. _If our priorities remain unchanged,_ we could get to this in a month or two. If you'd like to contribute a PR, we'd certainly prioritize a review.

**Comment by sethiyash** [comment]
looks like we have closed the requirement of `localResource` filter of which @joaopapereira is talking about on closing [#272](https://github.com/vmware-tanzu/carvel-kapp/issues/272). 
@cppforlife  so we just now have to add a new flag to filter the resources present on the cluster by label right ? and what all commands will be supporting it ?

**Comment by renuy** [comment]
Available in release 0.41.0.

**Comment by renuy** [comment]
@cameronbraid, this feature is now available as part of v0.41.0 .
Do checkout it out, and provide your feedback.
Thanks

**Comment by cameronbraid** [comment]
@renuy This is fantastic - sorry it took me a while to reply.

This feature makes my development workflow so much better.

I can now kapp deploy into a cluster with okteto enabld deployments, and have them ignored, using the following filter :

```
kapp deploy --diff-filter '{"existingResource": {"labels": ["interactive.dev.okteto.com="]}}'
```

**Comment by cameronbraid** [comment]
Actually, my previous filter wasn't quite right as it filtered out new resources, and had wrong label selector.

The following works

```
kapp deploy --diff-filter '{"not":{"existingResource": {"labels":["dev.okteto.com=true"]}}}'
```
