### ISSUE TITLE
Explore `kapp` incorporating externally-applied Resources

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/kapp#194]
**Describe the problem/challenge you have**
I am `kapp deploy`'ing a 3rd party product that installs one or more Resources on which my deployment is dependent. In particular, when such a product includes a controller that installs a CRD on my behalf, any CRs that I include in my `kapp deploy` will fail because that CRD will not have been registered in time.

**Describe the solution you'd like**
I want kapp to be aware of (and accommodate) Resources that are created by some external source (usually a Controller). If that means I need to add some annotation or other configuration in order to prompt `kapp` to do so, that's fine.

At the same time, I do not want to give up any confidence that when my `kapp deploy` completes, the corresponding software is up and running in my cluster.

**Questions**
- how should such resources be identified?
- how would they be incorporated into the ordering graph?
- what information about said resources is required to rendez-vous with them during reconciliation in the apply stage?
- should `kapp` adopt these resources? what are the consequences of doing so or not?
- how would `kapp` handle the deletion of said resources?

**Desired Outcomes**

- [ ] a light-weight proposal — a clear definition of the problem (in implementation terms) and potential solutions, suitable for asynchronous review.
- [ ] round of feedback/reviews — to "present" the proposal
- [ ] review of synthesized feedback - revisit proposal reworked based on feedback

**Anything else you would like to add:**
This request is based on reports in-the-wild of folks running into this chicken-and-egg problem; most notably, #52. However, the solution approach should not be limited to _just_ CRDs, but any resource that:
- can be depended on,
- created/deleted externally, yet,
- there is no current means to know when it has be deleted/reconciled.

Example 3rd Party products that have this "feature":
- [Gatekeeper](https://github.com/open-policy-agent/gatekeeper) (described in detail in #52)
- [Dex](https://github.com/dexidp/dex)

### Notes
- Timebox for the initial proposal is 4 days. As discussed at the community meeting, we'd recommend checking in and getting early feedback before the 4 days is up (around 2-3 days).

**Comment by jdef** [comment]
@dims we've been watching this issue too, awaiting a solution. our current solution to this dependency is pretty hacky and we'd like to drop the hacks in favor of native kapp support for such things.

**Comment by praveenrewar** [comment]
We have added support of [kapp.k14s.io/exists](https://carvel.dev/kapp/docs/latest/apply/#kappk14sioexists-available-in-v0430) annotation (available in v0.43.0) which can be used to wait for resources that are not owned by kapp.
