### ISSUE TITLE
Cluster-Fulfilled Resources

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/kapp#195]
`kapp` able to accommodate Resources that — instead of being provided through manifests by the end-user — are generated within the cluster itself.

Related issues:
- https://github.com/vmware-tanzu/carvel-kapp/issues/194
- https://github.com/vmware-tanzu/carvel-kapp/issues/297
- https://github.com/vmware-tanzu/carvel-kapp/issues/52
- https://github.com/vmware-tanzu/carvel-kapp/issues/192

**Comment by renuy** [comment]
closed as part of v0.43.0
