### ISSUE TITLE
Allow (re)deployment of resources that already have a kapp label

### ISSUE THREAD

**Issue by skinny** [k14s/kapp#20]
After messing up one of my kapp deployments, the kapp ConfigMap was lost. Redeploying the app generates a new label (id) but refuses to deployed because existing resources already have conflicting label.

After a small chat with @cppforlife he showed me :

- `kapp inspect -a label:kapp.k14s.io/app=...` to see what resources are associated
- `kapp delete -a label:kapp.k14s.io/app=...` to delete all of them 

It would be great to also have the option to `kapp deploy` with some kind of `overwrite` option to ignore the existing labels and just takeover the resources that are already there.

**Comment by cppforlife** [comment]
an alternative is to create a config map by hand with found app label (`kapp.k14s.io/app=...`). this may be less disruptive to existing resources in cluster (for example some resource refuse to be updated with a new label selectors -- StatefulSets possibly).

**Comment by cppforlife** [comment]
flag added in https://github.com/k14s/kapp/releases/tag/v0.8.0
