### ISSUE TITLE
kapp: Error: Blacklist errors on Config Maps

### ISSUE THREAD

**Issue by bsctl** [k14s/kapp#219]
**What steps did you take:**
I've a simple `yaml` file containing a `Config Map` like this `grafana.yaml` manifest

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
data:
  grafana.ini: |
    [log]
    format = json
    level = debug
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

```
**What happened:**
Apply the manifest

```
$ kapp deploy -a grafana -c -f config-map.yaml  
Target cluster 'https://cmp.example.com:6443' (nodes: cmp)

kapp: Error: Blacklist errors:
- Resource 'configmap/grafana (v1) namespace: cmp-system' has a blacklisted label 'kapp.k14s.io/is-app'
```

**What did you expect:**
An application deployed

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- kapp version `0.36.0`
- OS `ubuntu`
- Kubernetes version `v1.20.5`

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by cppforlife** [comment]
hey @bsctl, kapp creates a configmap with the name given to -a to store some metadata like unique label it generated. because you are also creating ConfigMap with the same name kapp notices a conflict and isnt allowing you to proceed. i would recommend changing a name to something like `-a grafana-app`

**Comment by bsctl** [comment]
@cppforlife thanks for comment. Any plan to fix this in short term? I love `kapp`. Thanks.

**Comment by cppforlife** [comment]
> Any plan to fix this in short term?

this comment [0] describes this same issue and potential improvement to kapp; however, we havent prioritized it yet. if you are feeling up for it we would welcome a PR implementing suggested approach.

[0] https://github.com/vmware-tanzu/carvel-kapp/issues/146#issuecomment-698960773

**Comment by cppforlife** [comment]
(closing in favor of #146 -- forgot that we had this issue already)
