### ISSUE TITLE
kapp delete change should precondition on uid when waiting for resource to be gone

### ISSUE THREAD

**Issue by cppforlife** [k14s/kapp#229]
**Describe the problem/challenge you have**

currently kapp when waiting for resource to be fully deleted off cluster, ignores that resource might have changed its uid. when uid changes it implies that resource has been deleted, and replaced by a different resource with a same name.

**Describe the solution you'd like**

we should _probably_ check on uid difference and see that if resource uid changed, then consider it as deleted. there is a nuance in this change though, we should probably continue waiting for the resource to be gone if uid changed, but resource still matches criteria for being within the app (currently happens today). 

**Anything else you would like to add:**

this came up during following steps:
- with kapp-controller 0.20.0-rc.1
- add pkg repo to a default ns
- add pkg repo to global packaging ns
- delete pkg repo from a default ns (this hangs for default wait timeout) because deleted package was replaced by package that is derived from global ns

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by aaronshurley** [comment]
This seems like a reasonable change or at least something to explore further. I'm going to move this to `carvel accepted` so that we can further discuss if/when to prioritize this.

**Comment by renuy** [comment]
release v0.40.0
