### ISSUE TITLE
Document "kapp app-group"

### ISSUE THREAD

**Issue by StarpTech** [k14s/kapp#236]
As titled. What's the exact difference between group and just deploy? I couldn't find any meaningful documentation.

**Comment by danielhelfand** [comment]
We do have some documentation on it here: https://carvel.dev/kapp/docs/latest/gitops/

Are there other things you would like to see covered in this section?

**Comment by StarpTech** [comment]
> Above command will deploy an application for each subdirectory in my-repo directory

That's useful information I'd expect part of the CLI help page.
