### ISSUE TITLE
provide a way to group resources so that they are applied in order

### ISSUE THREAD

**Issue by cppforlife** [k14s/kapp#24]
Example use case:

```
Deploy set of resources (eg configmap)
Deploy a job, wait for the job to complete (eg database migration)
Deploy another set of resources (eg service, ingress, deployment)
Wait for deployment to finish
Deploy another job and wait to finish (eg some type of script the app needs to run after a deployment)
Once everything is done, the program ends and my CI/CD pipeline is completed
```

from @bmaynard (https://kubernetes.slack.com/archives/CH8KCCKA5/p1561584027265500)

**Comment by cppforlife** [comment]
latest take on how ordering rules will be implemented: https://gist.github.com/cppforlife/8fcc864c3efb39f3657f418bacae4e7f

**Comment by cppforlife** [comment]
might be useful to visualize via d3: http://bl.ocks.org/jose187/4733747

**Comment by nimakaviani** [comment]
probably better for the tool to output a dependency tree independent of the format. It can be transformed to a d3 network graph later on if needed.

**Comment by cppforlife** [comment]
added in https://github.com/k14s/kapp/releases/tag/v0.10.0
