### ISSUE TITLE
kapp inspect --raw should not show managed fields by default.

### ISSUE THREAD

**Issue by GrahamDumpleton** [k14s/kapp#241]
**Describe the problem/challenge you have**

Using ``kapp inspect --raw`` and it outputs overly verbose managed fields from resource.

**Describe the solution you'd like**

Should adopt convention ``kubectl`` has taken of not showing managed fields by default and only show them when ``--show-managed-fields=true`` is passed as an option.

See ``show-managed-fields`` option in:

* https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#get

**Anything else you would like to add:**

Nope.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

cc @jorgemoralespou

**Comment by jorgemoralespou** [comment]
This was included in kubectl 1.21 as a response to the community (https://github.com/kubernetes/kubernetes/issues/90066).
