### ISSUE TITLE
retry network errors

### ISSUE THREAD

**Issue by revolunet** [k14s/kapp#258]
**Describe the problem/challenge you have**

Hi, i occasionaly get  this error while trying to apply some manifests with `kapp` : 

```
kapp: Error: waiting on reconcile deployment/backend (apps/v1) namespace: xxx-preprod:
  Errored:
    Listing schema.GroupVersionResource{Group:"", Version:"v1", Resource:"limitranges"}, namespaced: true: an error on the server ("error trying to reach service: dial tcp 10.0.0.1:443: connect: connection refused") 
```

The deployment gets applied correctly though

Looks like this is some kind of network error that could be retried

**Describe the solution you'd like**

Would be nice to handle this corner case as others in [isGeneralRetryableErr](https://github.com/vmware-tanzu/carvel-kapp/blob/d192479835b1fd83c704716d2a6189b59c706dd1/pkg/kapp/resources/resources.go#L431) maybe

**Anything else you would like to add:**

Thanks for kapp, a great helper !

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by renuy** [comment]
Sounds reasonable. would you want to contribute this change, or if not we will include it in our backlog.
