### ISSUE TITLE
Add rollout success/fail conditions

### ISSUE THREAD

**Issue by semoac** [k14s/kapp#26]
Please add a way to specify when the rollout should be considered finish.
My deploys have more than 300 pods each, so I don't want to wait for all the pods to be ready in every pipeline execution.

Maybe allows to specify a percentage from 0 to 100 or a more complex condition  via annotations on the resource.

**Comment by cppforlife** [comment]
added kapp.k14s.io/apps-v1-deployment-wait-minimum-replicas-available in https://github.com/k14s/kapp/commit/438ce917363c012c34209b35d391d72133415291. pending new release...

**Comment by rochacon** [comment]
@cppforlife any estimate on the release date? I've been using `kapp` in some CD pipelines and this will be handy to make sure it breaks if the rollouts fails.

**Comment by cppforlife** [comment]
> any estimate on the release date? 

im hoping today.

> this will be handy to make sure it breaks if the rollouts fails

do you expect that deployment waiting will "abort" in case rollout is failing? currently the feature above that's being added (https://github.com/k14s/kapp/blob/968f2b7a35e0fcc285d6e783fedbcd9e6321f914/pkg/kapp/resourcesmisc/ext_and_apps_vx_replica_set.go#L38-L49) is for deployment waiting to be cut short based on X number of replicas succeeding.

we did also add deployment fail-fast based on Progressing condition found on Deployment (https://github.com/k14s/kapp/commit/fe222825cf63a22e164a56f55fe9e05228479409). you will be able to configure it via `progressDeadlineSeconds` (https://github.com/kubernetes/api/blob/69e1bce1dad5403efb6e54485434efd219e86db7/apps/v1/types.go#L310). will this configuration solve your use case?

**Comment by cppforlife** [comment]
shipped in https://github.com/k14s/kapp/releases/tag/v0.10.0

**Comment by rochacon** [comment]
I have both of these cases, this is great, thank you @cppforlife !

**Comment by cppforlife** [comment]
ill close this then now. feel free to file new issue for improvements of deployment waiting.
