### ISSUE TITLE
GitHub workflow test-gh.yml does not run tests against latest version of k8s

### ISSUE THREAD

**Issue by 100mik** [k14s/kapp#268]
The script seems to be fetching an older version of Minikube (v1.10.0) to run tests against :

```
wget -O- https://github.com/kubernetes/minikube/releases/download/v1.10.0/minikube-linux-amd64 > /tmp/bin/minikube
chmod +x /tmp/bin/minikube
```

This version does not use the latest version of K8s by default.
We should change the script to get the latest stable version of Minikube.

Tests that were failing on K8s v1.21 (#261 ) should have ideally failed in the pipeline.

**Comment by 100mik** [comment]
A similar change should be made in `vmware-tanzu/carvel-kapp-controller` I believe

**Comment by renuy** [comment]
release v0.40.0
