### ISSUE TITLE
Increase Timeout of golangci-lint 

### ISSUE THREAD

**Issue by sethiyash** [k14s/kapp#269]
**Describe the problem/challenge you have** - 
golangci-lint check fails sometimes on new PR's throwing timeout error

**Describe the solution you'd like**
Increasing the timeout to maybe 5 mins as we already have in kapp-controller 

**Anything else you would like to add:**

Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this bug fixed as soon as possible"
👎 "There are more important bugs to focus on right now"

We are also happy to receive and review Pull Requests if you want to help fix this issue.

**Comment by cppforlife** [comment]
PR was merged.
