### ISSUE TITLE
kapp deploy --yes w/ tty redirected turns off progress notification by default

### ISSUE THREAD

**Issue by DTTerastar** [k14s/kapp#28]
kapp when run in a ci environment (tty redirected) it by default turns off all status output about the convergence of the deployment.  --tty fixes this, but the output without --tty is misleading to the point of making a user not realize the deploy was undertaken and failed.   

The only output without --tty is:  
```Error: timed out waiting after 15m0s```

**Comment by cppforlife** [comment]
fixed in https://github.com/k14s/kapp/commit/a389427338965db48bf0c21f1383f8ecf115da20

**Comment by cppforlife** [comment]
fixed in https://github.com/k14s/kapp/releases/tag/v0.10.0

**Comment by DTTerastar** [comment]
Works great! Thank you!
