### ISSUE TITLE
package repositories failed to get reconciled on the cluster.

### ISSUE THREAD

**Issue by soumyapanigrahi-code** [k14s/kapp#291]
**What steps did you take:**
While deploying kapp on Kubernetes cluster we are encountering a scenario where data.packaging.carvel.dev api-service appears to unavailable. This seems to be the case even though the POD instance(kapp controller) seems to be running.

**What happened:**

Because of this issue package repositories failed to reconcile on the cluster.

**What did you expect:**

Package repository instances should be reconciled successfully on the cluster.

**Anything else you would like to add:**

1. packaging-api  service exists in tanzu-system namespace as expected.
NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
`packaging-api   ClusterIP   10.19.250.254   <none>        443/TCP   22m`

2. v1alpha1.data.packaging.carvel.dev api-service instance is correctly pointing to packaging-api in tanzu-system:
NAME                                 SERVICE                      AVAILABLE   AGE
`v1alpha1.data.packaging.carvel.dev   tanzu-system/packaging-api   True        19m`

3. packaging-api  endpoint correctly resolves to the kapp-controller pod IP in tanzu-system namespace
NAME            ENDPOINTS         AGE
`packaging-api   10.16.1.7:10350   24m`

NAME                              READY   STATUS    RESTARTS   AGE   IP          NODE                                                  NOMINATED NODE   READINESS GATES
`kapp-controller-f765549c5-gt8kk   1/1     Running   0          27m   10.16.1.7   gke-soumya1sh-520250-210-default-pool-c00197c5-x4fc   <none>           <none>`

However the Package Repository status remains unchanged forever with the following message:
    Updated At:          2021-08-24T17:18:12Z
  Useful Error Message:  kapp: Error: unable to retrieve the complete list of server APIs: data.packaging.carvel.dev/v1alpha1: the server is currently unable to handle the request (possibly related issue: https://github.com/vmware-tanzu/carvel-kapp/issues/12)

kubectl logs:

`I0825 09:04:57.398210   29937 round_trippers.go:457] Response Status: 503 Service Unavailable in 1000 milliseconds
I0825 09:04:57.827450   29937 request.go:1347] body was not decodable (unable to check for Status): yaml: mapping values are not allowed in this context
I0825 09:04:57.827508   29937 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request
I0825 09:04:57.832371   29937 round_trippers.go:432] GET https://35.243.224.19/apis/data.packaging.carvel.dev/v1alpha1?timeout=32s
I0825 09:04:57.832403   29937 round_trippers.go:438] Request Headers:
I0825 09:04:57.832416   29937 round_trippers.go:442]     User-Agent: kubectl/v1.21.2 (darwin/amd64) kubernetes/092fbfb
I0825 09:04:57.832425   29937 round_trippers.go:442]     Accept: application/json, */*
I0825 09:04:58.150319   29937 round_trippers.go:457] Response Status: 503 Service Unavailable in 317 milliseconds
I0825 09:04:58.166684   29937 request.go:1347] body was not decodable (unable to check for Status): yaml: mapping values are not allowed in this context
I0825 09:04:58.166710   29937 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request
I0825 09:04:58.166759   29937 shortcut.go:89] Error loading discovery information: unable to retrieve the complete list of server APIs: data.packaging.carvel.dev/v1alpha1: the server is currently unable to handle the request
I0825 09:04:58.168458   29937 round_trippers.go:432] GET https://35.243.224.19/apis/data.packaging.carvel.dev/v1alpha1?timeout=32s
I0825 09:04:58.168486   29937 round_trippers.go:438] Request Headers:
I0825 09:04:58.168498   29937 round_trippers.go:442]     Accept: application/json, */*
I0825 09:04:58.168508   29937 round_trippers.go:442]     User-Agent: kubectl/v1.21.2 (darwin/amd64) kubernetes/092fbfb
I0825 09:04:58.491580   29937 round_trippers.go:457] Response Status: 503 Service Unavailable in 323 milliseconds
I0825 09:04:58.512093   29937 request.go:1347] body was not decodable (unable to check for Status): yaml: mapping values are not allowed in this context
I0825 09:04:58.512125   29937 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request
I0825 09:04:58.516098   29937 round_trippers.go:432] GET https://35.243.224.19/apis/internal.packaging.carvel.dev/v1alpha1/internalpackagemetadatas?limit=500
I0825 09:04:58.516126   29937 round_trippers.go:438] Request Headers:
I0825 09:04:58.516133   29937 round_trippers.go:442]     Accept: application/json;as=Table;v=v1;g=meta.k8s.io,application/json;as=Table;v=v1beta1;g=meta.k8s.io,application/json
I0825 09:04:58.516139   29937 round_trippers.go:442]     User-Agent: kubectl/v1.21.2 (darwin/amd64) kubernetes/092fbfb
I0825 09:04:58.974993   29937 round_trippers.go:457] Response Status: 200 OK in 458 milliseconds`

**Environment:**

This issue is observed across different K8S cluster types such as kind, gcp, etc. 

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by soumyapanigrahi-code** [comment]
non-issue. closing this issue as it was caused due to periodic overriding of ca certs used by kapp service.

**Comment by cppforlife** [comment]
debugging steps

```
$ kubectl get --raw  https://x.x.x.x/apis/data.packaging.carvel.dev/v1alpha1/serverresources.json -v=10
...
I0825 06:43:06.428537   39210 request.go:1068] Response Body: error trying to reach service: x509: certificate signed by unknown authority
I0825 06:43:06.428808   39210 helpers.go:216] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "the server is currently unable to handle the request",
  "reason": "ServiceUnavailable",
  "details": {
    "causes": [
      {
        "reason": "UnexpectedServerResponse",
        "message": "error trying to reach service: x509: certificate signed by unknown authority"
      }
    ]
  },
  "code": 503
}]
F0825 06:43:06.428890   39210 helpers.go:115] Error from server (ServiceUnavailable): the server is currently unable to handle the request
```

`error trying to reach service: x509: certificate signed by unknown authority` was indicating that something was wrong with cert setup for kc api server.

kc log had `I0824 16:56:17.455368      11 apiserver.go:188] Syncing CA certificate with APIServices` which indicates that it did setup certs.

turns out that APIService `k get apiservice v1alpha1.data.packaging.carvel.dev -oyaml` did not have spec.caBundle set because external installer was deleting it after it was added by kc.
