### ISSUE TITLE
Build and install Apple Silicon-targeted versions of kapp

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/kapp#292]
see vmware-tanzu/carvel#218

Do it like we do for ytt.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by 100mik** [comment]
Added the binary(kapp-darwin-arm64) and checksum to the [latest release](https://github.com/vmware-tanzu/carvel-kapp/releases/tag/v0.39.0). [This PR](https://github.com/vmware-tanzu/carvel-kapp/pull/293) adds the case to our `build-binaries.sh` script.

**Comment by 100mik** [comment]
[This PR](https://github.com/vmware-tanzu/homebrew-carvel/pull/17) updates homebrew to support this as well.

**Comment by renuy** [comment]
will be included in release v0.40.0

**Comment by renuy** [comment]
release v0.40.0
