### ISSUE TITLE
Granular ordering of CRDs/namespace-scoped resources

### ISSUE THREAD

**Issue by praveenrewar** [k14s/kapp#297]
**Describe the problem/challenge you have**
Currently the ordering of kapp is implemented in such a way that all the CRs are dependent on all the CRDs and all the namespaced resources are dependent on all the namespaces and so on.

**Describe the solution you'd like**
We should update the ordering graph in such a way that all the CRs are dependent on their respective CRDs, all the namespaced resources are dependent on their respective namespaces and so on.

**Anything else you would like to add:**

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritise our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by renuy** [comment]
available as part of v0.41.0
