### ISSUE TITLE
🐦 Tweet about v0.39.0 🐦 

### ISSUE THREAD

**Issue by adriens** [k14s/kapp#301]
# Context

I've implemented CI on the chocolatey repos and releasing the v0.39.0 cf https://github.com/adriens/chocolatey-kapp/issues/6

Once moderated, I'd like to retweet the official release annoucement, but for now, I only have the [v0.38.0](https://twitter.com/carvel_dev/status/1429833478611349508) one.

# Action

- [x] Can you please tweet about the [v0.39.0](https://github.com/vmware-tanzu/carvel-kapp/releases/tag/v0.39.0) release ?

**Comment by renuy** [comment]
Thanks @adriens for bringing this up.
cc: @microwavables

**Comment by adriens** [comment]
I'm in the starting blocks 😆

**Comment by microwavables** [comment]
@adriens here ya go! thank you! https://twitter.com/carvel_dev/status/1433409493291896834?s=20

**Comment by adriens** [comment]
Thanks, I'll retweet it today 😺

**Comment by adriens** [comment]
Here we go https://twitter.com/rastadidi/status/1433546675327422465
