### ISSUE TITLE
Add support for work with encrypted secrets using tools like ejson or sops

### ISSUE THREAD

**Issue by semoac** [k14s/kapp#32]
Hi.

It would be great if kapp was integrated with a tool like ejson to decrypt secrets on the go.
kubernetes-deploy (shopify) does something like this.

The idea is been able to commit secrets on the repo in a secure way.

Cheers.

**Comment by aegershman** [comment]
+1 this is a helpful feature of [helmfile (declarative helm chart tool)](https://github.com/roboll/helmfile#secrets) is the ability to specify a `secrets` which automatically decrypts and interpolates [values files encrypted via `mozilla/sops`](https://github.com/mozilla/sops) which can be stored in git. Here's are examples: [1](https://github.com/aegershman/concourse-local-on-helm/blob/master/minikube/config/concourse-web/secrets.yaml), [2](https://github.com/aegershman/concourse-local-on-helm/blob/master/.sops.yaml), [3](https://github.com/aegershman/concourse-local-on-helm/blob/master/minikube/helmfile.yaml#L19-L20). Not trying to hijack just adding some background context.

**Comment by cppforlife** [comment]
@semoac @aegershman my view on it has been to rely on power of piping ie `some-secrets-tool -f config/ | kapp deploy ...`. this way tools' responsibilities are very clear. are these tools not able to inject bunch of yaml files and decrypt them, before sending them to kapp?

ive also noted down some similar thoughts for secrets and ytt here: https://github.com/k14s/ytt/blob/develop/docs/injecting-secrets.md

**Comment by semoac** [comment]
@cppforlife you are right on many levels. Specially because that approach follows the unix philosophy but I still think it would be great if `kapp`  provides an alternative or way to do this and not just panic if an encrypted yaml file is present on the manifest directory.

Maybe, as a part of the `kapp.k14s.io/v1alpha1 Config` resource, a section `renderRules` could help us specify what to do when files with particular extensions are present. For example, when encounter a `*.enc.yaml` file, render it with `sops -d {{ .filePath }} ` or  with `ejson decrypt {{ .filePath }}` or `/app/hack/script.sh  {{ .filePath }}`  or even `cat /dev/null`.

**Comment by cppforlife** [comment]
> you are right on many levels. Specially because that approach follows the unix philosophy ... a section `renderRules` could help us specify what to do when files with particular extensions are present ...

why is it a problem to run tool before kapp? (especially if you agree on the unixy approach being being solid)

what if k14s org included a tool that helped you with decrypting files (a thin wrapped around sops or ejson)? would that make your workflow better?

> but I still think it would be great if kapp provides an alternative or way to do this and not just panic if an encrypted yaml file is present on the manifest directory.

what does the error look like right now?

**Comment by semoac** [comment]
> why is it a problem to run secrets tool before kapp? (especially if you agree on the unixy approach being being solid)

Not a problem but, in some cases, not so practical. In our case, we have 2, and some times 3, sets of secrets encrypted with different keys because they belong to different teams.

So my deploy line is like

kapp deploy -a core-api -n backend -f manifests/ -f <(sops -d /team1/secrets/secret.enc.yaml) -f <(sops -d /team2/secrets/secret.env.yaml) 

> 
> what if k14s org included a tool that helped you with decrypting files (a thin wrapper around sops or ejson)? would that make your workflow better?

Yes, this will allow me to create a better integration with my environment and hide the preparation, merge and validation of secrets in the pipeline.

> what does the error look like right now?

 ```
kapp deploy -a test-enc -f /srv/k8s/backend/core-api
panic: Expected version to be of format group/version: was ENC[AES256_GCM,data:1U3vGPhwXA==,iv:VfFOQXn/4GCboJ2uBWVlF5Xnp1Cvxaw4w0Z3AT6baxg=,tag:zmesv3lSBSrYvoQrF/VuxQ==,type:str]

goroutine 1 [running]:
github.com/k14s/kapp/pkg/kapp/resources.(*ResourceImpl).APIGroup(0xc000094c00, 0x0, 0x0)
	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/kapp/pkg/kapp/resources/resource.go:132 +0x226
github.com/k14s/kapp/pkg/kapp/resources.UniqueResourceKey.String(0x20d5dc0, 0xc000094c00, 0x0, 0x0, 0xc0003571f0, 0x0)
	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/kapp/pkg/kapp/resources/unique_resources.go:27 +0xc4
github.com/k14s/kapp/pkg/kapp/resources.UniqueResources.Resources(0xc000344480, 0x3, 0x4, 0x1e664a0, 0xc000175e60, 0xc000358d00, 0xc000094cb0, 0xc00015aa80)
	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/kapp/pkg/kapp/resources/unique_resources.go:45 +0x14e
github.com/k14s/kapp/pkg/kapp/app.Preparation.PrepareResources(0x20df800, 0xc0003df590, 0x207b860, 0xc0000105f0, 0xc000344480, 0x3, 0x4, 0x0, 0x0, 0x0, ...)
	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/kapp/pkg/kapp/app/preparation.go:23 +0x5b
github.com/k14s/kapp/pkg/kapp/cmd/app.(*DeployOptions).Run(0xc0003225a0, 0x0, 0xc000335c90)
	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/kapp/pkg/kapp/cmd/app/deploy.go:82 +0x340
github.com/k14s/kapp/pkg/kapp/cmd/app.NewDeployCmd.func1(0xc0004c2000, 0xc000094f80, 0x0, 0x4, 0xc000109d00, 0xc000335cf8)
	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/kapp/pkg/kapp/cmd/app/deploy.go:40 +0x2a
github.com/k14s/kapp/vendor/github.com/cppforlife/cobrautil.ReconfigureLeafCmd.func1(0xc0004c2000, 0xc000094f80, 0x0, 0x4, 0x0, 0x0)
	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/kapp/vendor/github.com/cppforlife/cobrautil/misc.go:67 +0x18f
github.com/k14s/kapp/vendor/github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc0004c2000, 0xc000094f80, 0x0, 0x4, 0x0, 0x0)
	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/kapp/vendor/github.com/cppforlife/cobrautil/misc.go:25 +0xaf
github.com/k14s/kapp/vendor/github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc0004c2000, 0xc000094f80, 0x0, 0x4, 0x0, 0x0)
	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/kapp/vendor/github.com/cppforlife/cobrautil/misc.go:25 +0xaf
github.com/k14s/kapp/vendor/github.com/spf13/cobra.(*Command).execute(0xc0004c2000, 0xc000094f00, 0x4, 0x4, 0xc0004c2000, 0xc000094f00)
	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/kapp/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/k14s/kapp/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0001f1400, 0xc0001f1400, 0xc0004306c0, 0x1c5c31e)
	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/kapp/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/k14s/kapp/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/kapp/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/kapp/cmd/kapp/kapp.go:26 +0x142
```

**Comment by cppforlife** [comment]
> kapp deploy -a core-api -n backend -f manifests/ -f <(sops -d /team1/secrets/secret.enc.yaml) -f <(sops -d /team2/secrets/secret.env.yaml)

im not too familiar with sops. how does sops know how to decrypt different team secrets in the above example? or is it same secret for all of them?

> Yes, this will allow me to create a better integration with my environment and hide the preparation, merge and validation of secrets in the pipeline.

do you place any of your more complex kapp invocations into a bash script or something similar?

**Comment by semoac** [comment]
> im not too familiar with sops. how does sops know how to decrypt different team secrets in the above example? or is it same secret for all of them?
`.sops.yaml` has rules on what to do depending on the file.

> do you place any of your more complex kapp invocations into a bash script or something similar?

Yes, a lot of preparation is made to ensure `kapp` will encounter simple `yaml` files. The `secrets` steps are the more complex but that is normal because of the problem. With other tools like `kubernetes-deploy` these steps are simpler thanks to the way it integrates `ejson`. In that caseis  simple  enough to standardize the secret sharing across all the projects/teams we have. I will love if `kapp` has some level of integration with a tool that can be used like that.
