### ISSUE TITLE
Bump go version to latest

### ISSUE THREAD

**Issue by aaronshurley** [k14s/kapp#320]
**Describe the problem/challenge you have**
We want to ensure that the code remains compatible with the latest versions so that we do not risk falling behind and on an unsupported version (note: go supports n-1 versions).

**Describe the solution you'd like**
The code runs on the latest version of go.

**Anything else you would like to add:**

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by renuy** [comment]
@aaronshurley , planning to bump to version 1.17.1 (latest stable).
