### ISSUE TITLE
Remove branch v0.40.0

### ISSUE THREAD

**Issue by nicholasdille** [k14s/kapp#321]
For version 0.40.0 you created a tag as well as a branch but with conflicting revisions. My Homebrew package for kapp is unable to figure out the correct revision for the tag v0.40.0. See my [PR](https://github.com/nicholasdille/homebrew-tap/pull/678 ) for the failed action. It would be greatly appreciated to remove the branch v0.40.0. It looks like this was created by mistake. Thanks in advance :-)

**Comment by praveenrewar** [comment]
@nicholasdille Unfortunately we can't access the PR link that you have shared. However, we have deleted the branch named v0.40.0 like you asked. Thanks a lot for bringing this to our notice. Also, do let us know if the issue is now resolved.

**Comment by nicholasdille** [comment]
@praveenrewar, thanks a lot for addressing this so quick. You are awesome!

I fixed the link in case you still want to take a look 😀

**Comment by nicholasdille** [comment]
The build now works correctly :-)

**Comment by praveenrewar** [comment]
Awesome :)
