### ISSUE TITLE
"Ownership errors" messages with label values are confusing 

### ISSUE THREAD

**Issue by garrettthomaskth** [k14s/kapp#33]
I just had an ownership problem caused by trying to deploy the same resources under two different app names. I received the following error:
Error: Ownership errors:
```Resource 'service/some-service (v1) namespace: demo' is associated with a different label value 'kapp.k14s.io/app=1566811645817612751'. ```
It would be more intuitive to give the app name in the error message instead of the label value.

**Comment by cppforlife** [comment]
also want to indicate which namespace app potentially belongs.

**Comment by cppforlife** [comment]
improved this error msg as mentioned in this comment: https://github.com/k14s/kapp/issues/79#issuecomment-598300810. v0.22.0 included this change.
