### ISSUE TITLE
🐦 Please tweet about v0.41.0 release 🐦 

### ISSUE THREAD

**Issue by adriens** [k14s/kapp#331]
Hi, could you please tweet about the [v0.41.0](https://github.com/vmware-tanzu/carvel-kapp/releases/tag/v0.41.0). So I can rewteet it. for the [choco announce](https://github.com/adriens/chocolatey-kapp/issues/8)

Thank you in advance. 🐱

**Comment by adriens** [comment]
https://github.com/adriens/chocolatey-kapp/issues/8

**Comment by renuy** [comment]
Thanks Adriens, will get this done asap.

**Comment by adriens** [comment]
Done 👏 
Thanks 😸 
https://twitter.com/rastadidi/status/1445472230662492169
