### ISSUE TITLE
Improve how the user can sort and filter app-changes while listing them

### ISSUE THREAD

**Issue by 100mik** [k14s/kapp#339]
**Describe the problem/challenge you have**
Today we do not provide any flags with the `app-change list` command which allows the user to filter or list changes for a particular time frame easily.

**Describe the solution you'd like**
Allowing the following flags will allow the user to find specific app-changes more effectively.

- `--before=<timestamp>`, `--after=<timestamp>`
    - Can be used to specify a time interval and list app-changes in that interval
- `--sort`
    - allowed values : `newest-first`,`oldest-first`
    - default value : `newest-first`
    - Let's the user decide how they want to list app-changes
- Would it make sense to have a `--duration` flag as well?
    - Example : `--duration 2h` gets changes for the past 2 hours 

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by 100mik** [comment]
This goes hand-in-hand with #338 and helps improve how the user interacts with app-changes.

**Comment by renuy** [comment]
Available as part of kapp v0.47.0
