### ISSUE TITLE
kapp delete fails when not allowed to list cluster namespaces

### ISSUE THREAD

**Issue by boazy** [k14s/kapp#34]
I have an RBAC setup where each user or service account has access only to a single namespace, and is not able to list namespaces at all.

It seems like kapp has made most commands work with such clusters at be807cdd0952ff2524281304ec25d1f844578798, by falling back to the namespace specified by the `-n` flag if listing namespace fails. Still, it seems like in some cases (such as when scanning for leftover resources after deleting an app), the list of fallback namespaces is specified as `nil` and kapp will not fallback:
https://github.com/k14s/kapp/blob/b53b922fc165869232c8fe95ce62d623e3b1336d/pkg/kapp/app/labeled_app.go#L45

This results with all resources being successfully deleted, but the delete command still failing because it cannot get a list of all namespace.

**Comment by cppforlife** [comment]
fixed in https://github.com/k14s/kapp/commit/08958dbefe97eafd454444c87c14f6432f7e4e23 with a bit of refactoring to consolidate NewIdentifiedResources call into one place. will be included in the next release shortly.

**Comment by boazy** [comment]
Amazing! Thank you!
