### ISSUE TITLE
While checking for resource existence with "Exist" function, exist func should also return the resource.

### ISSUE THREAD

**Issue by rohitagg2020** [k14s/kapp#344]
## Value Addition
Today, in the `resources.go` file, both the `Resources` interface and `ResourcesImpl` struct, has the following method definition for Exists method `Exists(Resource, ExistsOpts) (bool, error)`. It doesn't return actual Resource object. Thus, if the caller of the Exists method has to act on the Resource Obj, he has to do another `Get()` call to get the latest resource. By adding the resource obj among the objects returned by Exists func, we can gain some performance.

## Code Changes:

- Navigate to the resources.go file.
- Change the `Resources` Interface `Exists(Resource, ExistsOpts) (bool, error)`  to `Exists(Resource, ExistsOpts) (Resource, bool, error)`. 
- There are two implementation of this interface:
    - `FakeResources` in `identified_resources_list_test.go` file
    As there is no method body for this, just changing the method signature will be enough here.
    - `ResourcesImpl` in `resources.go` file
    Here, we need to change both method signature as well as method body. In method body, we need to create the Resource object similar to like we do in `Get` method of resources.go file. Keep in mind that Retry functionality has to be retained.
- This method is consumed directly in `identified_resources.go` file. We have to change the method signature of this function to return Resource Obj as well.
   https://github.com/vmware-tanzu/carvel-kapp/blob/b5d6a0aa7c6bbef9857b472ca70b8a8c38a70d1a/pkg/kapp/resources/identified_resources.go#L101
- Now, we have to change the places from where `Exists` method of `identified_resources.go` is called. Those places are:
   - In add_or_update_change file
   https://github.com/vmware-tanzu/carvel-kapp/blob/b5d6a0aa7c6bbef9857b472ca70b8a8c38a70d1a/pkg/kapp/clusterapply/add_or_update_change.go#L102
   - In delete_change file
   https://github.com/vmware-tanzu/carvel-kapp/blob/b5d6a0aa7c6bbef9857b472ca70b8a8c38a70d1a/pkg/kapp/clusterapply/delete_change.go#L63
   - In labeled_resources.go file
   https://github.com/vmware-tanzu/carvel-kapp/blob/b5d6a0aa7c6bbef9857b472ca70b8a8c38a70d1a/pkg/kapp/resources/labeled_resources.go#L222 
   In labeled_resources.go file, immediately after this, we check if it exist and then make another call to get the Resource. Now, we can remove that and put this returned Resource Obj over the channel `resCh`
   https://github.com/vmware-tanzu/carvel-kapp/blob/b5d6a0aa7c6bbef9857b472ca70b8a8c38a70d1a/pkg/kapp/resources/labeled_resources.go#L228-L234

## Acceptance Criteria
As these methods are consumed internally, acceptance criteria for this will be to:
-  Adopt the changed method signature at all the places it is called from( as mentioned above).
-  No compilation error. To compile, you can navigate to the root directory i.e. `carvel-kapp` and run this script `hack/build.sh`.

**Comment by shubham14bajpai** [comment]
Hi @rohitagg2020 I would like to take this up.

**Comment by rohitagg2020** [comment]
Sure, feel free to make a PR.

**Comment by renuy** [comment]
@shubham14bajpai , would love to hear more from you on kapp and other carvel tools. Here is our [website](https://carvel.dev/).  We are active on  carvel [slack channel](https://kubernetes.slack.com/archives/CH8KCCKA5) too. see you there.

**Comment by renuy** [comment]
released as part of v0.43.0

**Comment by renuy** [comment]
@shubham14bajpai, thank you for your contribution
