### ISSUE TITLE
verify kubernetes.io/metadata.name annotation on Namespace resource behaviour

### ISSUE THREAD

**Issue by cppforlife** [k14s/kapp#348]
**Describe the problem/challenge you have**
I think in latest k8s, cluster started adding kubernetes.io/metadata.name annotation to Namespace resources. im not sure if we need to add a deafult rebase rule or it already just works (because it gets added by admission control) -- not sure. lets verify this behaviour.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by rohitagg2020** [comment]
I tried creating the namespace via "kapp" on k8s server version 1.22.2. It did added `kubernetes.io/metadata.name` but I was able to create and delete it successfully via kapp. 
```
roaggarwal@roaggarwal-a01 config % kubectl get ns rohit -oyaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kapp.k14s.io/identity: v1;//Namespace/rohit;v1
    kapp.k14s.io/original: '{"apiVersion":"v1","kind":"Namespace","metadata":{"labels":{"kapp.k14s.io/app":"1633955127929178000","kapp.k14s.io/association":"v1.86935d4bbaaa82db22ee72e15d93290b"},"name":"rohit"}}'
    kapp.k14s.io/original-diff-md5: 9b6164a38d55b72e8c2c5ae43123d231
  creationTimestamp: "2021-10-11T12:25:28Z"
  labels:
    kapp.k14s.io/app: "1633955127929178000"
    kapp.k14s.io/association: v1.86935d4bbaaa82db22ee72e15d93290b
    kubernetes.io/metadata.name: rohit
  name: rohit
  resourceVersion: "27702"
  uid: d2bed971-9529-4253-b2a3-0b6e1cc4364a
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

**Comment by rohitagg2020** [comment]
Tried to reproduce the scenario but deploying the same namespace again doesnt show anything on diff. Hence closing the issue
