### ISSUE TITLE
Update tests to use testify/require instead of value comparisons and Fatal

### ISSUE THREAD

**Issue by praveenrewar** [k14s/kapp#349]
**Describe the problem/challenge you have**
Currently unit tests and e2e tests are using value comparisons and Fatal which is not very intuitive.

**Describe the solution you'd like**
We should update the tests to use testify/require which will make them more readable and the output would be very descriptive and concise in case the tests are failing.

**Anything else you would like to add:**
This has already been done for diff package, and the [PR](https://github.com/vmware-tanzu/carvel-kapp/pull/347) can be found here.
Update the tests for the following packages
- [x] pkg/kapp/diffgraph and pkg/kapp/matcher - @khan-ajamal
- [x] pkg/kapp/resources - @khan-ajamal
- [x] pkg/kapp/resourcemisc - @ShajithaMohammed
- [x] test/e2e - @ShajithaMohammed 

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by khan-ajamal** [comment]
Hi @praveenrewar i would like to take this up.

**Comment by praveenrewar** [comment]
@khan-ajamal Sure, thanks for contributing!

**Comment by rohitagg2020** [comment]
@khan-ajamal Please let us know how much you have progressed on the same.

**Comment by 100mik** [comment]
Thanks for the PR @khan-ajamal ! We are still accepting PRs for the remaining packages:
 - pkg/kapp/resources
 - pkg/kapp/resourcemisc
 - test/e2e

Feel free to comment on this thread if you would like to contribute to these! The changes expected are similar to ones in the PRs:
 - #354 
 - #347

**Comment by khan-ajamal** [comment]
Hi, @100mik I would love to take on the remaining tasks, will send PRs for them soon.

**Comment by 100mik** [comment]
That will be wonderful @khan-ajamal ! Putting your name against `pkg/kapp/resources`. We can tick them off as and when the PRs roll in.
Feel free to make a single PR or separate PRs for each package as per your convenience.
Cheers!

**Comment by ShajithaMohammed** [comment]
Hi @praveenrewar @100mik I would like to take up remaining packages - pkg/kapp/resourcemisc and test/e2e

**Comment by 100mik** [comment]
Sure! I will put your name against those.

**Comment by 100mik** [comment]
@ShajithaMohammed let's put together a PR for the `pkg/kappresourcemisc` package and we will move onto `test/e2e`!

**Comment by 100mik** [comment]
@ShajithaMohammed would you like to make a PR for the `test/e2e` package?

**Comment by ShajithaMohammed** [comment]
> @ShajithaMohammed would you like to make a PR for the `test/e2e` package?

Yes! @100mik

**Comment by 100mik** [comment]
Go for it!

**Comment by 100mik** [comment]
Great work on this @khan-ajamal and @ShajithaMohammed.
Would love to see you around on our [channel](https://kubernetes.slack.com/archives/CH8KCCKA5) on Kubernetes slack!
