### ISSUE TITLE
error message separator to indicate start of an error coming from the server

### ISSUE THREAD

**Issue by cppforlife** [k14s/kapp#369]
**Describe the problem/challenge you have**
current output
```
kapp: Error: Applying create packagemetadata/contour.community.tanzu.vmware.com (data.packaging.carvel.dev/v1alpha1) namespace: default:
  Creating resource packagemetadata/contour.community.tanzu.vmware.com (data.packaging.carvel.dev/v1alpha1) namespace: default: internalpackagemetadatas.internal.packaging.carvel.dev "contour.community.tanzu.vmware.com" already exists (reason: AlreadyExists)
```

proposed output:
```
kapp: Error: Applying create packagemetadata/contour.community.tanzu.vmware.com (data.packaging.carvel.dev/v1alpha1) namespace: default:
  Creating resource packagemetadata/contour.community.tanzu.vmware.com (data.packaging.carvel.dev/v1alpha1) namespace: default:
    API server says:
      internalpackagemetadatas.internal.packaging.carvel.dev "contour.community.tanzu.vmware.com" already exists (reason: AlreadyExists)
```

im hoping this will be helpful in clearly identifying what part of error message is from CLI vs k8s server.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen. If applicable a visual representation of the UX (ex: new CLI argument name, the behavior expected).]

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by renuy** [comment]
Thanks for adding this, @cppforlife.  This should help debug better.

**Comment by renuy** [comment]
The new line starts only iff the error message has a "colon space capital letter" 
(eg:-  ": InternalServerError").
It will not happen when its "colon space small letter" (eg:- ": internalServerError") 
this is due to the CLI library being used. we could change the CLI library to change the regex to include small letters, to start new line.

**Comment by cppforlife** [comment]
> we could change the CLI library to change the regex to include small letters, to start new line.

i think that would apply to too many cases where we dont want a line break

**Comment by renuy** [comment]
@sethiyash , maybe we could look at adding a prefix with capital letter?

**Comment by sethiyash** [comment]
Yeah. We can add some prefix (maybe `Message: `) to show error message in new line.

```
kapp: Error: Applying create packagemetadata/contour.community.tanzu.vmware.com (data.packaging.carvel.dev/v1alpha1) namespace: default:
  Creating resource packagemetadata/contour.community.tanzu.vmware.com (data.packaging.carvel.dev/v1alpha1) namespace: default:
    API server says:
      Message: internalpackagemetadatas.internal.packaging.carvel.dev "contour.community.tanzu.vmware.com" already exists (reason: AlreadyExists)
```

**Comment by renuy** [comment]
without adding the "Message: " prefix, it will look like:
```
kapp: Error: Applying create packagemetadata/contour.community.tanzu.vmware.com (data.packaging.carvel.dev/v1alpha1) namespace: default:
  Creating resource packagemetadata/contour.community.tanzu.vmware.com (data.packaging.carvel.dev/v1alpha1) namespace: default:
    API server says: internalpackagemetadatas.internal.packaging.carvel.dev "contour.community.tanzu.vmware.com" already exists (reason: AlreadyExists)
```

**Comment by cppforlife** [comment]
i think that's fine -- still solves the problem of delimiting whats being returned from the server.
