### ISSUE TITLE
Support versions field for CRDs

### ISSUE THREAD

**Issue by drzero42** [k14s/kapp#37]
kapp version: 0.12.0

When I recently tried to deploy cert-manager v0.10.0 along with a ClusterIssuer, kapp gave this error: `Error: Expected to find kind 'certmanager.k8s.io/v1alpha1/ClusterIssuer', but did not`.

With cert-manager v0.9.1 this works - I can deploy a ClusterIssuer alongside cert-manager in one go.

If I deploy cert-manager v0.10.0 and the ClusterIssuer CR independently it works.

Digging into what changed, I discovered that the CustomResourceDefinition for ClusterIssuer changed from using the (deprecated) `version` field to a `versions` list with a single entry ([documentation for version vs versions](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/#specify-multiple-versions).

**Comment by cppforlife** [comment]
fixed in https://github.com/k14s/kapp/commit/011251497cc376ea54e8464e16e9cf8119d7fe88. will be included in upcoming release.

**Comment by cppforlife** [comment]
shipped in https://github.com/k14s/kapp/releases/tag/v0.13.0
