### ISSUE TITLE
improve how repeated row content is shown within a column (in this example in namespace column)

### ISSUE THREAD

**Issue by Zanadar** [k14s/kapp#38]
During the TGIK viewing, Joe was using `kapp`, and he had great things to say about it! ~~But it looks like he found a bug:~~
<img width="1141" alt="Screen Shot 2019-09-27 at 4 47 17 PM" src="https://user-images.githubusercontent.com/5925347/65801180-7ba6cc80-e146-11e9-8bbd-5a96e67caa9e.png">

maintainer edit: it's a current UI behavior, read more details below...

**Comment by cppforlife** [comment]
currently `~` is used to shown for rows that have same content as row above. in this case `kpack-controller` row has the same namespace as `controller`, hence it shows `~`.

one downside of this is that `~` is also very close looking as `-` which indicates no namespace. ~ is also used for that repeating content as well, making things more confusing potentially.

one proposal is to remove namespace deduplication but that potentially will make things more noisy.

**Comment by cppforlife** [comment]
any thoughts @jbeba?

**Comment by Zanadar** [comment]
Sometimes people use `"` for this, like so:
kpack, one, two, three
", two, two, three

**Comment by cppforlife** [comment]
additional alteratives for repeating chars: `"`, `^`, `^^`, `~~~`

**Comment by cppforlife** [comment]
to improve table output:
- show `(cluster)` in namespace column: https://github.com/k14s/kapp/commit/e2a5937a34462adad1d3f7f0f15080b58555ab9f
- use `^` marker for dup content: https://github.com/k14s/kapp/commit/2049009d286d22e60d301a1c6640ce4325843eb3

will be available in v0.14.0

**Comment by cppforlife** [comment]
available in https://github.com/k14s/kapp/releases/tag/v0.14.0

![Screen Shot 2019-10-03 at 12 46 19 PM](https://user-images.githubusercontent.com/185847/66158940-d4a9b100-e5db-11e9-9204-d7079082dc05.png)
