### ISSUE TITLE
Can't deploy two apps into the same namespace

### ISSUE THREAD

**Issue by StarpTech** [k14s/kapp#398]
**What steps did you take:**
As titled.

```sh
kapp deploy --into-ns apps -a foo
kapp deploy --into-ns apps -a bar
```

**What happened:**

```sh
kapp: Error: Ownership errors:
- Resource 'ingress/hello-kubernetes (networking.k8s.io/v1) namespace: preview-apps' is already associated with a different app 'foo' namespace: default (label 'kapp.k14s.io/app=1640032910396211183')
- Resource 'deployment/hello-kubernetes (apps/v1) namespace: preview-apps' is already associated with a different app 'foo' namespace: default (label 'kapp.k14s.io/app=1640032910396211183')
- Resource 'persistentvolumeclaim/csi-pvc (v1) namespace: preview-apps' is already associated with a different app 'foo' namespace: default (label 'kapp.k14s.io/app=1640032910396211183')
- Resource 'service/hello-kubernetes (v1) namespace: preview-apps' is already associated with a different app 'foo' namespace: default (label 'kapp.k14s.io/app=1640032910396211183')
```

**Environment:**

- kapp version (use `kapp --version`): 0.43.0

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by praveenrewar** [comment]
@StarpTech The `into-ns` flag is used to place all the resources into the provided namespace, i.e. it overrides the `metadata.namespace` of every resource with the flag value. If you want to deploy the app in a specific namespace you should use the `--namespace` flag.

As for the error, you can't have one resource part of multiple kapp applications. So, when you try to deploy the second app with the same value for `into-ns`, it throughs an ownership error as the resource is already part of app `foo` (I am guessing that you have the same name for ingress, deployment, etc, in both the yamls, or you are using the same yaml).

**Comment by StarpTech** [comment]
@praveenrewar you're absolutely right. I mixed it up a bit. I could resolve it. Thank you!
