### ISSUE TITLE
kapp doesn't support colon separated KUBECONFIG

### ISSUE THREAD

**Issue by jaxxstorm** [k14s/kapp#4]
I use kubectl (and kubecfg) with a `KUBECONFIG` that looks like this:

```
/Users/lbriggs/.kube/config:/Users/lbriggs/.kube/config.d/dev-config.yml:/Users/lbriggs/.kube/config.d/prod-config.yml
```
When using `kapp` I get an error:

```
Error: Building Kubernetes config: stat /Users/lbriggs/.kube/config:/Users/lbriggs/.kube/config.d/dev-config.yml:/Users/lbriggs/.kube/config.d/prod-config.yml: no such file or directory
```

**Comment by cppforlife** [comment]
@jaxxstorm taking a look what's a better client-go way of doing it. Currently it just picks up one file: https://github.com/k14s/kapp/blob/develop/pkg/kapp/cmd/core/config_factory.go#L60-L75. will report back...

**Comment by cppforlife** [comment]
@jaxxstorm give [v0.3.0](https://github.com/k14s/kapp/releases/tag/v0.3.0) a try. i think it should now behave as you are used to with kubectl.

**Comment by jaxxstorm** [comment]
Confirmed working! Thanks!
