### ISSUE TITLE
Add checksums.txt to release artifacts

### ISSUE THREAD

**Issue by andrewrothstein** [k14s/kapp#406]
**Describe the problem/challenge you have**
Trying to validate checksums on released artifacts. No checksums.txt file published with release artifacts for kapp releases. See [here](https://github.com/vmware-tanzu/carvel-kapp/releases/tag/v0.43.0).

**Describe the solution you'd like**
In many of the other carvel tool repos the releases come with a checksums.txt file. For example ytt:0.38.0 publishes [this](https://github.com/vmware-tanzu/carvel-ytt/releases/download/v0.38.0/checksums.txt).

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by sethiyash** [comment]
Hi @andrewrothstein 
In kapp we generally put down the checksums in the release notes itself instead of putting them in checksums.txt file wouldn’t that help ? Any particular reason for which you want us to put them in checksums.txt file also ?

**Comment by andrewrothstein** [comment]
I'm trying to author an Ansible role that downloads and installs the release executables from GitHub. The Ansible get_url module can check the downloaded executables against a checksums file. Adding the checksums file to the release artifacts will make this easy. I like easy. Of the other carvel tools ytt, kbld, and imgpkg already include a checksums file in the release artifacts. Kapp and vendir don't. I notice that the build scripts look like a copy-paste job across the repos so doesn't look like it would be a big lift to get them all consistent in this way. What do you think? I'll attempt the PR if ur open to it.

**Comment by sethiyash** [comment]
@andrewrothstein Firstly thanks for sharing the detailed usecase. We have decided to add checksums file in our subsequent releases. If you are willing to raise a PR we are open to that as well.

**Comment by rohitagg2020** [comment]
Done as part of https://github.com/vmware-tanzu/carvel-kapp/issues/425
