### ISSUE TITLE
Gracefully accept resource defaults and other value defined during admission

### ISSUE THREAD

**Issue by scothis** [k14s/kapp#408]
**Describe the problem/challenge you have**

`kapp deploy` will take a blob of k8s yaml and do its best to make resources on the server match the desired state. The command's behavior is idempotent. That is a second running of the command should be a noop assuming the resources have not been updated since they were created. Unfortunately this is often not quite true, which causes near-meaningless changesets to accumulate on the sever, and causes extra load inside the API Server handling updates that end up resulting in no meaningful change. 

This behavior is caused most prominently by mutating web hooks during admission. It's common for a resource to define default values that are applied at admission time which makes the requested resource different than the admitted resource. The kapp docs currently suggest that the [user is responsible for defining their resource in a way that it will not have any new values set as defaults](https://carvel.dev/kapp/docs/latest/faq/#changes-detected-immediately-after-successful-deploy). This is user hostile as the behavior will likely be different depending on the specific environment.

kapp should be able to transparently handle mutations made to the desired resource at admission time without forcing the user to go through gymnastics.

The current behavior is more problematic when kapp is called in a control loop, like with kapp-controller.

**Describe the solution you'd like**

Requests to the Kubernetes API to create or update a resource will return the resource as it is admitted into the cluster. The returned resources will contain all of the defaulted and assigned values. The content of the requested resource and the admitted resource can be compared to get a diff of the values that were applied during admission.

For the next deploy of the app, the desired state can have this diff applied to it before comparing to the current state on the cluster. If the resource has not changed, then there is no need to issue an update. If the new desired state has changed in a such a way that the diff cannot be applied, or there is a meaningful change, then issue an update with the original desired resource, and capture the new admission diff for the next deploy.

Note: any mutation of a resource that happens after admission is not accounted for in this mechanism and is considered drift that *should* be "reverted" by kapp on the next deploy.

The diff for each resource can be written into the ConfigMap backing the app.

**Anything else you would like to add:**

While a bit different in scope, this basic approach is implemented in reconciler-runtime when creating child resources. [Apply patch before update](https://github.com/vmware-labs/reconciler-runtime/blob/v0.4.0/reconcilers/reconcilers.go#L677-L686). [Generate patch after update](https://github.com/vmware-labs/reconciler-runtime/blob/v0.4.0/reconcilers/reconcilers.go#L706-L713). The goal of this code is not to eliminate unnecessary updates, only to reduce them. If anything goes wrong, an update based on the desired state is executed without the diff.

Refs #394 #395

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by cppforlife** [comment]
(suggested behaviour is already what kapp does. i reached out to @scothis to see what prompted him to think otherwise. waiting for a reply here.)

**Comment by cppforlife** [comment]
im going to close this @scothis. feel free to reopen with more info.
