### ISSUE TITLE
Provide a way to set a limit of configmaps to keep at deploy time

### ISSUE THREAD

**Issue by ngauje** [k14s/kapp#42]
In case of strict quota policy on configmaps, we have to manually launch garbage collection via `kapp app-change gc --max 2`.
It would be a good improvement to have a way to set it as an app config. Or to be able to set it at deploy time.

**Comment by cppforlife** [comment]
@ngauje do you think adding a flag to deploy command would satisfy your use case (you would have to provide it every time you deploy)? or do you think this should be a global setting of sorts?

**Comment by ngauje** [comment]
@cppforlife I think a flag to the deploy command is a preferable solution (more explicit)

**Comment by cppforlife** [comment]
added `--app-changes-max-to-keep` flag (default 200) to deploy in https://github.com/k14s/kapp/commit/a19e872300e771fd41b380bbd76720fad388ae47. coming in next release.

**Comment by ngauje** [comment]
Great !
