### ISSUE TITLE
Identify and Automate the test cases execution before doing a release

### ISSUE THREAD

**Issue by rohitagg2020** [k14s/kapp#425]
**Describe the problem/challenge you have**
There are certain test cases that should be run every time before we release a kapp to ensure that it behaves as expected. 

**Describe the solution you'd like**

- [x] Identify the test cases to be run.
- [x] Identify what all can be automated.
- [x] Automate them and add to the release process.

**Comment by rohitagg2020** [comment]
Will be working on this as well as part of this:

`Add checksums.txt to release artifacts` #406

**Comment by renuy** [comment]
Moving this to the prioritized backlog

**Comment by rohitagg2020** [comment]
Completed. Version 0.47.0 should be an automated release.
