### ISSUE TITLE
Rename module from "github.com/k14s/kapp" to "github.com/vmware-tanzu/carvel-kapp"

### ISSUE THREAD

**Issue by praveenrewar** [k14s/kapp#437]
**Describe the problem/challenge you have**

We've moved our git repos from the k14s org to the vmware-tanzu org.
The module path of a project to match that of the GitHub repo where it lives.

**Describe the solution you'd like**
Rename the module and all references to it.

**Anything else you would like to add:**
This is part of vmware-tanzu/carvel#153

---

To Do:
- [ ] Perform the rename
- [ ] Give the Carvel repos a review (example: vmware-tanzu/carvel) to see if any repos are consuming kapp so that they can be updated.
- [ ] broadcast this change in slack channels so that any consumers are aware.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by renuy** [comment]
linked to  https://github.com/vmware-tanzu/carvel/issues/153
