### ISSUE TITLE
Please 🐦 about v0.46.0 release

### ISSUE THREAD

**Issue by adriens** [k14s/kapp#438]
Hi,
can you please tweet about [v0.46.0](https://github.com/vmware-tanzu/carvel-kapp/releases/tag/v0.46.0) so i'll can retweet it ❔ 🙏

**Comment by praveenrewar** [comment]
cc @microwavables

**Comment by microwavables** [comment]
Done! https://twitter.com/carvel_dev/status/1496199210286338055?s=20&t=mOF4eQhI0OZPclY1YclECg
Thanks @adriens

**Comment by adriens** [comment]
🐦 ✔️
