### ISSUE TITLE
Allow versioned resources to have failed previous versions.

### ISSUE THREAD

**Issue by lnhrdt** [k14s/kapp#461]
**Describe the problem/challenge you have**

When I use versioned job resources for data migrations, it would be useful to allow failed previous versions. In my development workflow these data migrations often fail and require developers to diagnose and deploy new versions. Ideally in this workflow:
- Developers don't need to manually modify (i.e. delete) k8s resources. Our deployments are all managed by a CI system, triggered when developers push code to git.
- Developers can keep the history of the failed previous versions.

**Describe the solution you'd like**

Allow versioned resources to have failed previous versions. Perhaps through annotation configuration.

**Anything else you would like to add:**

This is a followup from Slack:
https://kubernetes.slack.com/archives/CH8KCCKA5/p1647720204911829

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by renuy** [comment]
@lnhrdt , adding this to the unprioritized backlog.  hoping to get to it soon, however feel free to raise a PR and we could get it reviewed in priority.
Thanks

**Comment by praveenrewar** [comment]
I also noticed that using the `--diff-changes` flag when there is already a failed version present in the app results in a panic as shown below.
```bash
kapp -n apps deploy -a versioned-job-test -f app-succeed.yaml -c                                                                             
Target cluster 'https://192.168.64.81:8443' (nodes: minikube)

@@ create job/my-job-ver-3 (batch/v1) namespace: versioned-job-test @@
  ...
  5,  5       kapp.k14s.io/versioned: ""
      6 +     kapp.k14s.io/versioned-keep-original: ""
  6,  7     creationTimestamp: "2022-03-21T06:18:16Z"
  7,  8     generation: 1
  ...
 90, 91           - -c
 91     -         - exit 1
     92 +         - exit 0
 92, 93           image: alpine:3.15.0
 93, 94           name: my-job
@@ noop job/my-job-ver-2 (batch/v1) namespace: versioned-job-test @@
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1fe8e95]

goroutine 1 [running]:
github.com/k14s/kapp/pkg/kapp/diff.TextDiffView.String({0x0, {0xc000d4f5c0, 0x2, 0x2}, {0x2, 0x1, 0x1}})
	github.com/k14s/kapp/pkg/kapp/diff/text_diff_view.go:37 +0xd5
github.com/k14s/kapp/pkg/kapp/clusterapply.(*ChangeSetView).Print(0xc000b18568, {0x26beba0, 0xc000425680})
	github.com/k14s/kapp/pkg/kapp/clusterapply/change_set_view.go:37 +0x387
github.com/k14s/kapp/pkg/kapp/cmd/app.(*DeployOptions).calculateAndPresentChanges(_, {_, _, _}, {_, _, _}, {{0xc000a8f200, 0x1, 0x1}}, ...)
	github.com/k14s/kapp/pkg/kapp/cmd/app/deploy.go:423 +0xc85
github.com/k14s/kapp/pkg/kapp/cmd/app.(*DeployOptions).Run(0xc0003e82c0)
	github.com/k14s/kapp/pkg/kapp/cmd/app/deploy.go:149 +0x8a5
github.com/k14s/kapp/pkg/kapp/cmd/app.NewDeployCmd.func1(0xc0007a0960, {0x243e817, 0xa, 0x226b5a0})
	github.com/k14s/kapp/pkg/kapp/cmd/app/deploy.go:55 +0x1d
github.com/k14s/kapp/pkg/kapp/cmd.NewKappCmd.func1.1(0xc0001d1c80, {0xc0001b84d0, 0x0, 0x7})
	github.com/k14s/kapp/pkg/kapp/cmd/kapp.go:128 +0xce
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0x11f65a5, {0xc0001b84d0, 0x0, 0x7})
	github.com/cppforlife/cobrautil@v0.0.0-20200514214827-bb86e6965d72/misc.go:45 +0x6d
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc000880400, {0xc0001b84d0, 0x0, 0x7})
	github.com/cppforlife/cobrautil@v0.0.0-20200514214827-bb86e6965d72/misc.go:45 +0x6d
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc0004bb680, {0xc0001b84d0, 0x0, 0x7})
	github.com/cppforlife/cobrautil@v0.0.0-20200514214827-bb86e6965d72/misc.go:45 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc0004bb680, {0xc0001b8460, 0x7, 0x7})
	github.com/spf13/cobra@v1.1.3/command.go:852 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004bac80)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
main.nonExitingMain()
	github.com/k14s/kapp/cmd/kapp/kapp.go:42 +0x153
main.main()
	github.com/k14s/kapp/cmd/kapp/kapp.go:21 +0x19
```

**Comment by praveenrewar** [comment]
Created a separate [issue](https://github.com/vmware-tanzu/carvel-kapp/issues/491) for the panic.

**Comment by renuy** [comment]
Available as part of kapp v0.47.0

**Comment by lnhrdt** [comment]
@renuy and @praveenrewar I got to try this out today.

I was looking for mention of the behavior in the docs, but couldn't find anything. Through experimentation it appears to me that it's the default new behavior, and no configuration is necessary. Is that correct?

**Comment by praveenrewar** [comment]
> Through experimentation it appears to me that it's the default new behavior, and no configuration is necessary. Is that correct?

That's correct, this is the default new behaviour.

Do you think it would be helpful to mention this in the docs?

**Comment by lnhrdt** [comment]
Hey @praveenrewar! Thank you so much for this change. I know it was done a couple months ago but it's a great change for my pipelines.

Since it is the default behavior I don't think it's important to mention in the docs. I believe a new user who never saw the old behavior would find no surprises. I think I was just confused because I had an assumption it was going to be configurable. It's nice and simple!
