### ISSUE TITLE
Conflicts should show some diff

### ISSUE THREAD

**Issue by dprotaso** [k14s/kapp#471]
**Describe the problem/challenge you have**
When a conflict occurs it's not actionable

```
kapp: Error: Applying update deployment/activator (apps/v1) namespace: 24f0bc17-06dc-424b-a9db-8d4e744d7790:
  Failed to update due to resource conflict  (approved diff no longer matches):
  Updating resource deployment/activator (apps/v1) namespace: 24f0bc17-06dc-424b-a9db-8d4e744d7790:
  API server says:
    Operation cannot be fulfilled on deployments.apps "activator": the object has been modified; please apply your changes to the latest version and try again (reason: Conflict)
```

**Describe the solution you'd like**
It would good to show what the diff is so I could potentially write a rebase rule

**Anything else you would like to add:**
N/A

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by rohitagg2020** [comment]
@dprotaso , Can you share the steps to reproduce the issue?

**Comment by dprotaso** [comment]
Have a deployment with an HPA and no rebaseRules

**Comment by rohitagg2020** [comment]
We can improve the error to show what is causing the conflict:

```kapp: Error: Applying update deployment/activator (apps/v1) namespace: 24f0bc17-06dc-424b-a9db-8d4e744d7790:
  Failed to update due to resource conflict  (approved diff no longer matches):
  Updating resource deployment/activator (apps/v1) namespace: 24f0bc17-06dc-424b-a9db-8d4e744d7790:
  API server says:
    Operation cannot be fulfilled on deployments.apps "activator": the object has been modified; please apply your changes to the latest version and try again (reason: Conflict)
    Conflict occured because of the following: {[spec.replicas]}
```

**Comment by rohitagg2020** [comment]
Note to Self: Error originates from https://github.com/vmware-tanzu/carvel-kapp/blob/a1a44c0d7f0fea302f77e091cf5bc4d9e3a3779e/pkg/kapp/clusterapply/add_or_update_change.go#L120

`OpsDiff` doesn't have any compare method to compare two `OpsDiff` and get output in a readable manner. Most probably, we have to enhance the code.
