### ISSUE TITLE
HPA: keep the server chosen values per default

### ISSUE THREAD

**Issue by universam1** [k14s/kapp#473]
Thank you for providing a great tool!

**Describe the problem/challenge you have**

The fix to add [custom rebaseRules to “prefer” server chosen value for spec.replicasUsers](https://carvel.dev/kapp/docs/v0.46.0/hpa-deployment-rebase/) on each repo is often unknown or forgotten by developers. It requires additional training and makes it harder for the developers to use Kapp for their deployments.

**Describe the solution you'd like**

Kapp should detect when a deployment does not explicitly define `replicas` and thus keep the server chosen value without resetting it.
Alternatively, apply the above config "fix" if a HPA is part of the app.

Similar to https://github.com/vmware-tanzu/carvel-kapp/issues/80#issuecomment-596640209

**Comment by rohitagg2020** [comment]
Thank you for the encouraging words @universam1

**Comment by rohitagg2020** [comment]
@universam1 I would like to understand more about this scenario. Can we hop on a jump a zoom call if possible?
