### ISSUE TITLE
augment default rules with ordering for App/PackageInstall

### ISSUE THREAD

**Issue by cppforlife** [k14s/kapp#476]
**Describe the problem/challenge you have**

want App/PackageInstall CR to work nicely (in context of ordering with service account/RBAC) out of the box in kapp deploy/delete.

**Describe the solution you'd like**

add default rules?

upsert:
- upsert clusterrolebinding after service account and clusterrole
- upsert PackageInstall/App should after service account and RBAC

deletion:
- delete PackageInstall/App before service account and RBAC

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by renuy** [comment]
adding to un-prioritized backlog for now.
