### ISSUE TITLE
kapp should add namespaces used by resources to fallback namespaces

### ISSUE THREAD

**Issue by cppforlife** [k14s/kapp#479]
**Describe the problem/challenge you have**
currently fallback namespace for finding existing resources is only single namespace that is specified via --namespace flag. fallback namespaces are needed by kapp cannot find deployed resources easily (across all namespace). this becomes important if configuration is deployed across multiple namespaces but kapp does not have perms to list all namespaces (which is desirable if you have a lot of namespaces on the cluster). 

**Describe the solution you'd like**
currently only --namespace is added as fallback namespace. we should populate fallback namespaces with namespaces used by resources at the time of the deploy, and since we track them in state configmap used a union of them with new namespaces on the next deploy.

to reproduce: kapp deploy a set of resources across 3 namespaces but make sure that service-account/user given to kapp does not have ability to list namespaces on the cluster.

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by renuy** [comment]
adding to unprioritized backlog as of now.

**Comment by praveenrewar** [comment]
Available in [v0.53.0](https://github.com/vmware-tanzu/carvel-kapp/releases/tag/v0.53.0)
