### ISSUE TITLE
Unable to deploy large CRD due to annotation max size limit (262144 characters)

### ISSUE THREAD

**Issue by siwyd** [k14s/kapp#48]
Issue created after Slack chat: https://kubernetes.slack.com/archives/CH8KCCKA5/p1573575958163800

I'm unable to deploy a certain CRD because of the size of the kapp.k14s.io/original annotation:
```
Error: Applying update customresourcedefinition/alertmanagers.monitoring.coreos.com (apiextensions.k8s.io/v1beta1) cluster: Saving record of last applied resource: Updating resource customresourcedefinition/alertmanagers.monitoring.coreos.com (apiextensions.k8s.io/v1beta1) cluster: CustomResourceDefinition.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 characters (reason: Invalid)
```

kubectl apply works because of the JSON encoding of the annotation it seems (added benefit: doesn't clutter kubectl describe output):
```
Annotations:  kapp.k14s.io/identity: v1;/apiextensions.k8s.io/CustomResourceDefinition/alertmanagers.monitoring.coreos.com;apiextensions.k8s.io/v1beta1
              kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"creationTimestamp":null,"name...
```

**Comment by cppforlife** [comment]
crd that's ended up being too big: https://raw.githubusercontent.com/coreos/prometheus-operator/v0.34.0/example/prometheus-operator-crd/alertmanager.crd.yaml

**Comment by cppforlife** [comment]
fix is in https://github.com/k14s/kapp/commit/11b66ef2370060abe9b408e5fa5708c8c67ea665. will be included in upcoming release.

**Comment by siwyd** [comment]
Awesome!

**Comment by cppforlife** [comment]
shipped in https://github.com/k14s/kapp/releases/tag/v0.15.0

**Comment by gabegorelick** [comment]
With https://github.com/vmware-tanzu/carvel-kapp/pull/430 merged, deploying large resources should no longer be an issue.

**Comment by gutmensch** [comment]
I think PR #430 misinterpreted the the API definition of max annotation size. Please check https://github.com/kubernetes/apimachinery/blob/2e9c2280ae353a81c2f50c98c75cbb69658d58f0/pkg/api/validation/objectmeta.go#L36-L67

256KB is the max *total size* of all annotation kv pairs together and not of a *single value* of any annotation key, what the for loop in https://github.com/carvel-dev/kapp/pull/430/files#diff-75f9d0a72d68750d5be444bf6fb2f566961c9ba171b41cb215424f88a0dc535bR106 checks.

I have discovered the same issue, where the sum is exactly bigger than 256KB, although the value of the CRD is smaller (roughly 240KB), so I am still stuck with the problem of halting kapp sync.
```
  usefulErrorMessage: |-
    kapp: Error: update customresourcedefinition/applicationsets.argoproj.io (apiextensions.k8s.io/v1) cluster:
      Saving record of last applied resource:
        Updating resource customresourcedefinition/applicationsets.argoproj.io (apiextensions.k8s.io/v1) cluster:
          API server says:
            CustomResourceDefinition.apiextensions.k8s.io "applicationsets.argoproj.io" is invalid: metadata.annotations:
              Too long: may not be more than 262144 bytes (reason: Invalid)
```
