### ISSUE TITLE
Delete multiple deployments simultaneously via single kapp delete cmd

### ISSUE THREAD

**Issue by scothis** [k14s/kapp#50]
It would be nice to delete multiple deployment with a single command

```
kapp delete -a app1 -a app2 -a app3
```

Currently, only the last app (app3) is deleted and the others are ignored. This is common behavior with cobra, but can be surprising for users.

**Comment by cppforlife** [comment]
the alternative option is to disallow multiple -a specifications.

im not sure if we should allow multiple -a on delete as then deploy command becomes asymmetric with delete. thoughts about alternative mentioned above?

**Comment by scothis** [comment]
> the alternative option is to disallow multiple -a specifications.

Cobra doesn't make this easy

**Comment by cppforlife** [comment]
can just switch to slice type and assert on length == 1.

**Comment by scothis** [comment]
> can just switch to string slice type and assert on length == 1.

The docs for the command will then be misleading as they will show the flag as an array. Also, this pattern applies to *every* other flag. I'd leave it alone and let Cobra manage the behavior generically.

**Comment by cppforlife** [comment]
but if so, what does it mean to kapp deploy -a foo -a another-one ...?

**Comment by cppforlife** [comment]
after thinking some more, i think at this point kapp should stick with one deployment for -a flag for now to maintain consistency with other commands.
