### ISSUE TITLE
Add flag to disable default label scoping rules

### ISSUE THREAD

**Issue by praveenrewar** [k14s/kapp#563]
### Discussed in https://github.com/vmware-tanzu/carvel-kapp/discussions/212

<div type='discussions-op-text'>

<sup>Originally posted by **cppforlife** April 17, 2021</sup>
Currently it's possible to disable label scoping feature per resource via annotation. We've seen that when users are migrating and they have existing Deployments it results in an annoying error for changing immutable field (spec.selector). We should figure out how to disable this feature.

we cannot simply change the kapp's default since we already have existing deploys out there (this would be a breaking change). one idea is to disable it for new deployments; however, that may not be great either if users are expecting this behavior for their new deployments as well (e.g. in CI you deploy test deployment every time).

what can we do to improve experience?</div>

**Comment by praveenrewar** [comment]
Related: #214

**Comment by praveenrewar** [comment]
We can probably add a flag to disable label scoping for all the resources present in an app. Relevant [slack thread](https://kubernetes.slack.com/archives/CH8KCCKA5/p1659016664874299).

**Comment by renuy** [comment]
Released as part of v0.52.0
