### ISSUE TITLE
[question] Move to 3-way merging?

### ISSUE THREAD

**Issue by ioben** [k14s/kapp#58]
Updating resources can result in the removal of changes made at runtime. For example Kubernetes adds annotations to persistent volume claims that are deleted when a second deploy is run. Helm also moved to a 3-way merging strategy during the release of Helm 3.

This Helm issue contains the reasoning behind the decision to move: https://github.com/helm/helm/issues/3805

And the eventual PR: https://github.com/helm/helm/pull/6124

**Comment by cppforlife** [comment]
hey @ioben, kapp explicitly decided to _not_ do 3 way merge, and instead allow the user to specify how to resolve "conflicts". here is our thinking:

- you as an operator have a set of files (input files given to kapp via -f) which state what is the desired
- cluster has some state that needs to be converged to whatever input files specify, with one exception: in some cases cluster is the source of truth for certain information (but not most) and will maintain that state on resources (common examples: some annotation on Deployment, clusterIP on Service, etc.)

given information above there are multiple ways to converge: make assumptions about how to merge things (basic 3 way merge), be explicit about how to merge things (kapp with its rebase rules), and just override.

overriding is not really an option as it removes potentially important cluster changes.

regarding explicit vs implicit, we decided to go with the explicit option. kapp allows users to add [rebase rules](https://github.com/k14s/kapp/blob/master/docs/config.md) to specify exactly which information to retain from existing resources. that gives control to the user to decide what's important to be kept based on cluster state and what's not. this method ensures that there are no _surprising_ changes left in the cluster (if 3 way merge was used, then user cannot confidently know how final resource will look like; ... imagine if you had a field `allowUnauthenticatedRequests: true` in some resource that someone flipped on in your cluster, and your configs never specified it; it would not be removed unless you decide to also specify this field in your configs).

kapp comes with some common k8s rebase rules. you can see them via `kapp deploy-config`.

**Comment by cppforlife** [comment]
hopefully that answered your question. ill close it at this point. feel free to reopen for more discussion.

**Comment by ioben** [comment]
Hey @cppforlife, appreciate the detailed answer to this! I'll need to dig into the rebase rules further. I had previously seen them, but honestly didn't quite understand what they were for till now.

Thanks!

**Comment by cppforlife** [comment]
@ioben if you have some ideas in how to make docs better in this regard, it would be much appreciated.
