### ISSUE TITLE
kapp does not replace ConfigMap or Secret name in initContainers when using versioned resources

### ISSUE THREAD

**Issue by lirsacc** [k14s/kapp#59]
HI,

While experimenting with kapp we've noticed that the ConfigMap and Secret references were not replaced in the `initContainers` block (it works for `containers`) when using versioned resources.

We've solved it by including a modified version of the default config which adds (what we think are) the correct `resourceMatchers` entries, but I reckon they should be included by default so the expectation around `containers` and `initContainers` are the same.

Happy to provide our changes to the default config as a PR, although I am not sure if they are complete past fixing our issue.

**Comment by cppforlife** [comment]
> Happy to provide our changes to the default config as a PR, although I am not sure if they are complete past fixing our issue.

yeah, let's do a PR.
