### ISSUE TITLE
Move `TestAppKindChangeWithMetadataOutput` to a separate file

### ISSUE THREAD

**Issue by 100mik** [k14s/kapp#604]
Today `TestAppKindChangeWithMetadataOutput` resides in `app_change_test.go`.
However, it does not have anything to do with the `app-change` command group.

This should be moved to a separate file (maybe `app_metadata_output_test.go`)

**Comment by 100mik** [comment]
A quick snack for someone looking to contribute!

**Comment by EdwinWalela** [comment]
Is this still required? `app_metadata_output_test.go` doesn't seem to exist was it renamed?
