### ISSUE TITLE
`dep check` fails

### ISSUE THREAD

**Issue by ekcasey** [k14s/kapp#61]
I was trying to hack around with `kapp` but I ran into issues with the dependencies. On `master` I see
```
$ dep check
# Gopkg.lock is out of sync:
github.com/k14s/kapp-controller/pkg/apis/kappctrl/v1alpha1: imported or required, but missing from Gopkg.lock's input-imports
gopkg.in/yaml.v2: imported or required, but missing from Gopkg.lock's input-imports
k8s.io/api/apps/v1: imported or required, but missing from Gopkg.lock's input-imports
k8s.io/api/batch/v1: imported or required, but missing from Gopkg.lock's input-imports
k8s.io/apimachinery/pkg/util/validation: imported or required, but missing from Gopkg.lock's input-imports
k8s.io/client-go/discovery: imported or required, but missing from Gopkg.lock's input-imports
k8s.io/client-go/kubernetes/scheme: imported or required, but missing from Gopkg.lock's input-imports
github.com/spf13/cobra/doc: in Gopkg.lock's input-imports, but neither imported nor required

# vendor is out of sync:
github.com/aryann/difflib: hash of vendored tree not equal to digest in Gopkg.lock
github.com/cppforlife/cobrautil: hash of vendored tree not equal to digest in Gopkg.lock
github.com/cppforlife/go-cli-ui: hash of vendored tree not equal to digest in Gopkg.lock
github.com/cppforlife/go-patch: hash of vendored tree not equal to digest in Gopkg.lock
github.com/k14s: unused project
k8s.io/apimachinery: hash of vendored tree not equal to digest in Gopkg.lock
k8s.io/client-go: hash of vendored tree not equal to digest in Gopkg.lock
```

Am I missing something?

Also, it would be nice if `kapp` migrated to go modules.

**Comment by cppforlife** [comment]
@ekcasey yup, there are some modifications to vendor directory that are present currently. need to circle back and fix those. ive stayed away from modules so far to let things settle. i was planning to try them out in go 1.14.

**Comment by rochacon** [comment]
@cppforlife I'm interested in helping with this and #64. I'm trying to embed some `kapp` functionality into another application and the lack of Go modules support and the vendor changes has been a blocker for it.

Could you point me out on the changes made to the vendor directory? Seems to me that a quick approach to this would be forking the changed dependencies, applying the changes there and pointing go.mod/dep to the fork repo. With this we would fix the `dep check` call and enable Go modules to work, while we work in getting those changes to the upstream projects.

**Comment by cppforlife** [comment]
> I'm trying to embed some kapp functionality

do drop by our slack, im curious to hear more (since it also has implications about what's a public interface as a library).

> Could you point me out on the changes made to the vendor directory?

they should be in the vendor directory, checked in. you would have to see diff if you redownload them (ie re-run dep ensure).

ill take a look today/tomorrow to see what it is at this point and see if i can upstream/fork. there should be fairly little amount of changes.

**Comment by rochacon** [comment]
@cppforlife I'll join kapp Slack and ping you soon. IIRC, the diff was quite large last time I checked, but I might have done something wrong so I'll check it again.

**Comment by cppforlife** [comment]
dep check succeeds on develop now.

**Comment by cppforlife** [comment]
closing this one now. regarding go modules transition -> https://github.com/k14s/kapp/issues/64
