### ISSUE TITLE
Feature parity to kubectl diff

### ISSUE THREAD

**Issue by lukasmrtvy** [k14s/kapp#65]
It would be great to have feature parity to `kubectl diff`. ( exit with code different than 0, if is there any diff )

- exit code 0 for no diff
- exit code 1 for diff/error

Thanks

**Comment by cppforlife** [comment]
to be implemented:

--diff-exit-codes (bool; default false). when it's set exit codes will indicate if there are changes detected: 0 - unused, 1 - any error, 2 - no changes, 3 - one or more change

**Comment by cppforlife** [comment]
implemented in https://github.com/k14s/kapp/commit/3b3102ef2ef8ccbbe9fbed1665cb58db8ab587d9. will be including in upcoming release.

**Comment by cppforlife** [comment]
shipped in https://github.com/k14s/kapp/releases/tag/v0.17.0. docs in https://github.com/k14s/kapp/blob/develop/docs/diff.md#controlling-diff-via-deploy-flags
