### ISSUE TITLE
Resource 'configmap/simple-app (v1) namespace: default' has a disallowed label 'kapp.k14s.io/is-app'

### ISSUE THREAD

**Issue by everesio** [k14s/kapp#686]
**What steps did you take:**
Deploying example https://github.com/vmware-tanzu/carvel-kapp/blob/develop/examples/simple-app-example/config-2.yml
`kapp deploy -a simple-app -f examples/simple-app-example/config-2.yml`

**What happened:**
Received the following error:
``` 
kapp: Error: Disallowed labels errors:
- Resource 'configmap/simple-app (v1) namespace: default' has a disallowed label 'kapp.k14s.io/is-app'
```

**What did you expect:**
Successful deployment

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- kapp version (use `kapp --version`):
``` 
kapp version 0.54.2
Succeeded
```

- OS (e.g. from `/etc/os-release`):
``` 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
```

- Kubernetes version (use `kubectl version`)
``` 
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2023-01-04T19:18:50Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4+k3s1", GitCommit:"c3f830e9b9ed8a4d9d0e2aa663b4591b923a296e", GitTreeState:"clean", BuildDate:"2022-08-25T03:45:26Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by praveenrewar** [comment]
Hi @everesio! kapp creates a ConfigMap with the same name as that of the app name to store some metadata, and in this case the app name you have provided is `simple-app` and there is already a CM present in the example with the same name, which leads to this conflict.
Can you try using a different app-name (anything other than `simple-app`)?

**Comment by praveenrewar** [comment]
> kapp creates a ConfigMap with the same name as that of the app name

You can also opt in to a newer behaviour which adds a suffic to the app name to generate the name of the metadata CM. More details [here](https://carvel.dev/kapp/docs/v0.54.0/configmap-migration/).
In future, we will be making this as the default behaviour.

**Comment by praveenrewar** [comment]
Related to https://github.com/carvel-dev/kapp/issues/146

**Comment by everesio** [comment]
Same problem with different name

```
➜  kapp git:(develop) kapp deploy -a simple-app2 -f examples/simple-app-example/config-2.yml

kapp: Error: Disallowed labels errors:
- Resource 'configmap/simple-app (v1) namespace: default' has a disallowed label 'kapp.k14s.io/is-app'
```

**Comment by everesio** [comment]
Same problem with setting `KAPP_FQ_CONFIGMAP_NAMES=true` or `KAPP_FQ_CONFIGMAP_NAMES=false`

**Comment by 100mik** [comment]
Could you do a `kapp ls -A` ? The example you are using seems to have a config map called `simple-app` and you might have an older app with the name.
The environment variables should do the job, but it will help us better if we know what is on your cluster 🤔

**Comment by praveenrewar** [comment]
@everesio You might wanna run `kapp delete -a simple-app` before deploying the app again, or deleting the CM `simple-app` should also do the trick. Even though the creation of app failed with an error (from your initial post), it would still have created the metadata ConfigMap for the app which is causing an issue now.

**Comment by everesio** [comment]
`kapp delete -a simple-app` helped. 
After that `export KAPP_FQ_CONFIGMAP_NAMES=true` works as well.
Thank you.
