### ISSUE TITLE
Example failed: "Error: Expected to find kind 'networking.istio.io/v1alpha3/Gateway'"

### ISSUE THREAD

**Issue by hongchaodeng** [k14s/kapp#7]
Hi, I'm reporting the playground example:
```
kapp deploy -a knative -f examples/knative-v0.2.1/release-no-mon.yml
```

Tried on Katacoda, it failed:
```
Error: Expected to find kind 'networking.istio.io/v1alpha3/Gateway', but did not
```

Please take a look and give me a hand. Thanks in advance!

**Comment by cppforlife** [comment]
@hongchaodeng before installing knative you must first install istio (examples/istio-*/istio.yml)

```
kapp deploy -a istio -f https://raw.githubusercontent.com/k14s/kapp/develop/examples/istio-v1.0.2/istio.yml
```

**Comment by cppforlife** [comment]
closing. feel free to reopen if my suggestion did not help.

**Comment by hongchaodeng** [comment]
@cppforlife 
Thanks for your reply. I'm finding kapp very cool and want to blog about it. I am doing it in spare time.

I have the following issue when installing istio:
```
Error: waiting on add customresourcedefinition/virtualservices.networking.istio.io (apiextensions.k8s.io/v1beta1) cluster errored: unable to retrieve the complete list of server APIs: rbac.istio.io/v1alpha1: the server could not find the requested resource
```

Could you help with it?

**Comment by nimakaviani** [comment]
what is the output of the following command when you run it against your cluster?

```
kubectl get pods -n istio-system
```

**Comment by cppforlife** [comment]
> Thanks for your reply. I'm finding kapp very cool and want to blog about it. I am doing it in spare time.

that's great, looking forward to reading it.

regarding error you are seeing, does it happen consistently? im trying to reproduce it on katacoda but no luck. i think there might be some retry logic inside k8s client library, but it may not be flexible enough. will update shortly.

**Comment by cppforlife** [comment]
@hongchaodeng i;ve added https://github.com/k14s/kapp/commit/310f5fb498906175f876c2363a98f9f1d4ba0de6 to increase number of retries.

**Comment by cppforlife** [comment]
closing as v0.5.0 includes above commit with a supposed fix. feel free to reopen.
