### ISSUE TITLE
`--dangerous-disable-gk-scoping` should only be available in `kapp deploy`

### ISSUE THREAD

**Issue by praveenrewar** [k14s/kapp#750]
During `kapp deploy`, we scope the listing of resources to only the GKs of the resources provided through `-f`, but we don't scope the listing in `kapp insepct` or `kapp deploy`, hence the flag `--dangerous-disable-gk-scoping` should only be made available in the `kapp deploy` command.

**Environment:**

- kapp version (use `kapp --version`):
- OS (e.g. from `/etc/os-release`):
- Kubernetes version (use `kubectl version`)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by praveenrewar** [comment]
If anyone wants to work on this issue:
- We need to move [this](https://github.com/carvel-dev/kapp/blob/5770b806d63a3557096b77eee6df007aef5a2982/pkg/kapp/cmd/app/resource_types_flags.go#L27) flag to [deploy_flags.go](https://github.com/carvel-dev/kapp/blob/develop/pkg/kapp/cmd/app/deploy_flags.go).
- Update the same at https://github.com/carvel-dev/kapp/blob/5770b806d63a3557096b77eee6df007aef5a2982/pkg/kapp/cmd/app/deploy.go#L248

**Comment by hernandanielg** [comment]
Hey @praveenrewar I haven't seen the code but will give this a try!!! 😅 - wish me luck!

**Comment by praveenrewar** [comment]
Thank you so much @hernandanielg!! I have assigned the issue to you. Good luck :)
