### ISSUE TITLE
`kapp app-group deploy` should order based on folder names

### ISSUE THREAD

**Issue by Baune8D** [k14s/kapp#755]
**What steps did you take:**
Deploy any app using `kapp app-group deploy`

**What happened:**
App deployment order is randomized on every execution.

**What did you expect:**
App deployment order should be alphabetically based on folder names.

**Anything else you would like to add:**
When reading directory using `ioutil.ReadDir` the ordering is correct, but when assigning to the result map here: https://github.com/carvel-dev/kapp/blob/df3cfc8d74bf79d52e96f8d1c1296d6f553f048b/pkg/kapp/cmd/appgroup/deploy.go#L137 ordering gets randomized.

**Environment:**

- kapp version (use `kapp --version`): 0.56.0
- OS (e.g. from `/etc/os-release`): macOS Ventura
- Kubernetes version (use `kubectl version`) 1.25.7

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by rjtch** [comment]
hey @Baune8D  i would like to work on this task

**Comment by praveenrewar** [comment]
Thank you for showing interest in the fixing this @rjtch! I am assigning the issue to you, let me know if you need any help with it.

**Comment by rjtch** [comment]
Hey @praveenrewar I would like to use a this library https://github.com/wk8/go-ordered-map to fix it. Is it okay or do you have any recommendations?

**Comment by praveenrewar** [comment]
Hey @rjtch! I noticed that you are using a slice in your PR, which is what I would have recommended as well 🚀
