### ISSUE TITLE
Service with type LoadBalancer might never has a loadBalancerIP

### ISSUE THREAD

**Issue by bryanl** [k14s/kapp#78]
I was using kapp to deploy [contour](https://github.com/projectcontour/contour). It hangs at the end:

```text
10:34:33AM: ongoing: reconcile service/envoy-external (v1) namespace: projectcontour
10:34:33AM:  ^ Load balancer ingress is empty
10:34:33AM:  L ok: waiting on endpoints/envoy-external (v1) namespace: projectcontour
```

According to the API docs for `loadBalancerIP` which hints on load balancer configurations being cluster provider specific

> [...] This feature depends on whether the underlying cloud-provider supports specifying the loadBalancerIP when a load balancer is created. This field will be ignored if the cloud-provider does not support the feature.

This means that depending on the cloud provider, this field will never have a value, so kapp will not ever complete successfully.

The bit of code that performs the check lives here:

https://github.com/k14s/kapp/blob/1d1d63a2909f387914c19e5869d5264876855e25/pkg/kapp/resourcesmisc/core_v1_service.go#L41-L45

**Comment by cppforlife** [comment]
yeah waiting behaviour isnt really standardized within k8s community (arguably in some cases there may not even be a reasonable thing to wait for), hence kapp has specialized waiting logic for some common resources. it's described here: https://github.com/k14s/kapp/blob/develop/docs/apply-waiting.md. there is no clear way to know if LBs in the env will ever "assigned" to a service.

there is `kapp.k14s.io/disable-wait` annotation that could be applied to a resource to let kapp know to avoid waiting entirely. ive resorted to relying on configuration generation tool to decide whether such annotation should be added (for example to all load balancers) based on some indication that LBs in particular env never get assigned.
