### ISSUE TITLE
Update cron-job.yml

### ISSUE THREAD

**Issue by satyampsoni** [k14s/kapp#792]
**What steps did you take:**
I was trying the command `kapp deploy -a hellocron -f cron-job.yml -y` and got an error shown in the screenshot.
![image](https://github.com/carvel-dev/kapp-controller/assets/94950988/dcfc876f-4c66-4ef3-a4d1-5a3d323b8959)
`apiVersion: batch/v1beta1` is not supported for the newer version of Kubernetes rather than `apiVersion: batch/v1`.

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`):
- Kubernetes version (use `kubectl version`)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by praveenrewar** [comment]
Transferring this issue to carvel-dev/kapp as it seems more relevant there.

**Comment by praveenrewar** [comment]
@satyampsoni I think you are trying to deploy a CustomResource of kind CronJob and the CustomResourceDefinition doesn't exist on the cluster. You would need the CRD on the cluster before you can create a CustomResource, or you can deploy both of them together using kapp and they will be automatically ordered and the CRD will be created first and then the CR.

Could you share what your expectation was in this case?
