### ISSUE TITLE
kapp error when svcat server is not available

### ISSUE THREAD

**Issue by lionelvillard** [k14s/kapp#8]
I'm getting this error when using `kapp` on a cluster with a bad svcat instance:

```
Error: unable to retrieve the complete list of server APIs: servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request```

Maybe `kapp` should ignore this?

**Comment by cppforlife** [comment]
wouldnt ignoring that error potentially hide some resources? seems like fixing underlying problem is better.

**Comment by cppforlife** [comment]
closing this. feel free to reopen if you have more thoughts on this topic.
