### ISSUE TITLE
How to ignore system generated annotations?

### ISSUE THREAD

**Issue by yujunz** [k14s/kapp#80]
Some annotations and attributes are added by system. Deploy from `kapp` seems deleting them.

```
--- update persistentvolumeclaim/juicefs-pvc (v1) namespace: chaos-sut
  ...
  2,  2   metadata:
  3     -   annotations:
  4     -     pv.kubernetes.io/bind-completed: "yes"
  5     -     pv.kubernetes.io/bound-by-controller: "yes"
  6     -     volume.beta.kubernetes.io/storage-provisioner: csi.juicefs.com
  7,  3     creationTimestamp: "2020-03-08T03:47:50Z"
  8,  4     finalizers:
  ...
 24, 20     storageClassName: juicefs-sc
 25     -   volumeMode: Filesystem
 26, 21     volumeName: pvc-7eb42232-0567-4115-a5cc-4c48af07bf66
 27, 22   status:
```

How can I keep them unchanged?

**Comment by cppforlife** [comment]
hey @yujunz, ive taken this example and threw in a doc page: https://github.com/k14s/kapp/blob/develop/docs/rebase-pvc.md. it's similar to https://github.com/k14s/kapp/blob/develop/docs/hpa-deployment-rebase.md. you can find more info on this page: https://github.com/k14s/kapp/blob/develop/docs/config.md about rebase rules.

**Comment by yujunz** [comment]
Nice. This is exactly what I needed.

Is it possible to make it built-in config? I think the pv annotations are most likely populated by controller.

**Comment by cppforlife** [comment]
yeah, i could see additing these annotations to default set of rebase rules (`kapp deploy-config` already shows that we do a few things for PVCs).
