### ISSUE TITLE
[apply retry] Retry if API-server instance is shut down

### ISSUE THREAD

**Issue by jkbschmid** [k14s/kapp#82]
If a k8s instance has multiple API-servers, one of which is being scaled down, existing websocket connections will be terminated and kapp will fail with:

> kapp: Error: waiting on reconcile destinationrule/istio-policy (networking.istio.io/v1alpha3) namespace: istio-system: errored: Listing schema.GroupVersionResource{Group:"apiextensions.k8s.io", Version:"v1beta1", Resource:"customresourcedefinitions"}, namespaced: false: Get https://api.cf4k8s.istio.shoot.canary.k8s-hana.ondemand.com/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions?labelSelector=kapp.k14s.io%2Fassociation%3Dv1.4ea2426af853c41012e6a53e19d4a3b1: http2: server sent GOAWAY and closed the connection; LastStreamID=64781, ErrCode=NO_ERROR, debug=""

# Feature request

kapp should use retries to cope with API server instances being scaled down.

**Comment by cppforlife** [comment]
interesting, i was pretty sure we already do retries, will check what's going on in this case.

**Comment by cppforlife** [comment]
> http2: server sent GOAWAY and closed the connection

it's interesting that this is how api-server "drains" connection.

**Comment by jkbschmid** [comment]
> it's interesting that this is how api-server "drains" connection.

IMO, the only thing the API-server can do to properly drain connections is to 1) wait for a certain period for the connections to be terminated and, once this period is over 2) send a GOAWAY and terminate connections itself. 
Therefore, kapp should be able to handle such connection terminations.

**Comment by cppforlife** [comment]
included in https://github.com/k14s/kapp/releases/tag/v0.31.0
