### ISSUE TITLE
support FORCE_COLOR env var to show colors in gitlab-ci

### ISSUE THREAD

**Issue by marekm71** [k14s/kapp#84]
I started using kapp to manage the cluster, and I wanted to configure it with gitlab-ci and I came across one problem, there are no colors in the gitlab-ci terminal, while everything works fine locally. Changing the --color = "true" flag does nothing. Anyone had a similar problem?

Here is an example, zero colors, while locally all changes are marked. https://gitlab.com/marek_m71/kapp

**Comment by cppforlife** [comment]
hmm. interesting can you link to a log that should have colors in; i couldnt quite find them in gitlab ui.

**Comment by marekm71** [comment]
Here is a link to the pipeline that has no colors: https://gitlab.com/marek_m71/kapp/-/jobs/470603719
The repository is publicly available and it is possible to add changes and run and view pipelines.

**Comment by cppforlife** [comment]
forked color repo into k14s/color. changed up support for FORCE_COLOR just a bit and switch kapp to that repo: https://github.com/k14s/kapp/commit/e84c90a9406780d78271793c9fb715837e17ef42. will be included in next release.

**Comment by cppforlife** [comment]
shipped https://github.com/k14s/kapp/releases/tag/v0.23.0. feel free to reopen if FORCE_COLOR is not enough.
