### ISSUE TITLE
Update `--preflight` flag to no longer follow the `Check=true` format

### ISSUE THREAD

**Issue by everettraven** [k14s/kapp#893]
In some discussions around https://github.com/carvel-dev/carvel/pull/729 it's come to my attention that with all preflight checks being disable by default, it doesn't make much sense to require the enabling of preflight checks to follow the format of `--preflight=Check=true,OtherCheck=true,...` and could instead follow the format of `--preflight=Check,OtherCheck,...`. This makes it follow an "enabler" pattern where all preflight checks must be explicitly enabled

**Comment by everettraven** [comment]
@tmshort expressed interest in working on this.

**Comment by everettraven** [comment]
@100mik @praveenrewar What are your thoughts on this?

**Comment by praveenrewar** [comment]
@everettraven Sounds good to me! Thanks you so much for all that you are doing 🙇🏻
