### ISSUE TITLE
Unclear what to provide to `kapp logs --pod-name`

### ISSUE THREAD

**Issue by pianohacker** [k14s/kapp#91]
The `-m, --pod-name` flag to `kapp logs` is very useful for quickly getting a filtered set of logs, but it's somewhat unclear from the help text what to provide.

`Set partial pod name to filter logs` seems to imply that, e.g., `kapp logs -a app -m my-pod` would get logs for `my-pod-55cfdc8f8f-dchpf`. I was able to figure out from a code dive that a glob is expected (`kapp logs -a app -m 'my-pod*`), but I think that noting it in the help text would be useful.

**Comment by cppforlife** [comment]
help message improvements: https://github.com/k14s/kapp/commit/34e30a10978965ed7f8681691b6e67a797edd98a

> Set pod name to filter logs (% acts as wildcard, e.g. 'app%')

**Comment by cppforlife** [comment]
included in v0.24.0
