### ISSUE TITLE
[ordering] provide a visual way to know order of changes to be applied

### ISSUE THREAD

**Issue by cppforlife** [k14s/kapp#92]
one idea is to add a flag --diff-graph that shows something like this: https://github.com/k14s/kapp/blob/1ef797e6e07a5e5626e62135464489a1164b5e96/pkg/kapp/diffgraph/change_graph_test.go#L65-L79. another might be spinning up a tiny http server that draws some html table.

**Comment by jorgemoralespou** [comment]
I would opt for the most simple way, as one usually relies on the summary to get that info. I wonder if people never found the lack of order information in the summary annoying. Most of the times of you don't use order I guess it doesn't matter, but when using order this information is important and currently the only way to know if order is correct is by deploying the application to the cluster.

**Comment by cppforlife** [comment]
we added --diff-ui-alpha to show tree that is used for ordering. we actually used it a few times to debug ordering while development. lets see how far it gets us and we can always iterate further.

**Comment by jorgemoralespou** [comment]
Thanks. I wonder how you come up with the flag names `-diff-ui-alpha` :-D

**Comment by cppforlife** [comment]
it would have been --diff-ui (since all other diff related flags start with --diff), but some folks wanted to indicate that this was an alpha level flag hence alpha suffix.

**Comment by jorgemoralespou** [comment]
And then when it promotes to stable will the flag change? This is really weird from a users point of view.
